stock_tickers = {'ABB': {'ticker': '17979', 'description': 'ABB India Ltd'},
                 'ABCAPITAL': {'ticker': '7310', 'description': 'Aditya Birla Capital Ltd'},
                 'ABFRL': {'ticker': '946826', 'description': 'Aditya Birla Fashion and Retail Ltd'},
                 'ACC': {'ticker': '17980', 'description': 'ACC Ltd'},
                 'ADANIENT': {'ticker': '17984', 'description': 'Adani Enterprises Ltd'},
                 'ADANIPORTS': {'ticker': '18294', 'description': 'Adani Port and Special Economic Zone Ltd'},
                 'ADANIPOWER': {'ticker': '17985', 'description': 'Adani Power Ltd'},
                 'AJANTPHARM': {'ticker': '947273', 'description': 'Ajanta Pharma Ltd'},
                 'ALKEM': {'ticker': '962425', 'description': 'Alkem Laboratories Ltd'},
                 'AMARAJABAT': {'ticker': '17997', 'description': 'Amara Raja Batteries Ltd'},
                 'AMBUJACEM': {'ticker': '17998', 'description': 'Ambuja Cements Ltd.'},
                 'APOLLOHOSP': {'ticker': '18004', 'description': 'Apollo Hospitals Enterprises Ltd.'},
                 'APOLLOTYRE': {'ticker': '18005', 'description': 'Apollo Tyres Ltd'},
                 'ARVIND': {'ticker': '18008', 'description': 'Arvind Ltd.'},
                 'ASHOKLEY': {'ticker': '18010', 'description': 'Ashok Leyland Ltd.'},
                 'ASIANPAINT': {'ticker': '18011', 'description': 'Asian Paints Ltd.'},
                 'AUBANK': {'ticker': '1014099', 'description': 'AU Small Finance Bank Ltd'},
                 'AUROPHARMA': {'ticker': '18014', 'description': 'Aurobindo Pharma Ltd.'},
                 'AXISBANK': {'ticker': '18017', 'description': 'AXIS Bank Ltd'},
                 'BAJAJ-AUTO': {'ticker': '18020', 'description': 'Bajaj Auto Ltd'},
                 'BAJAJFINSV': {'ticker': '18023', 'description': 'Bajaj Finserv Ltd'},
                 'BAJAJHLDNG': {'ticker': '18024', 'description': 'Bajaj Holdings and Investment Ltd'},
                 'BAJFINANCE': {'ticker': '18022', 'description': 'Bajaj Finance Ltd'},
                 'BALKRISIND': {'ticker': '39853', 'description': 'Balkrishna Industries Ltd.'},
                 'BANDHANBNK': {'ticker': '1072999', 'description': 'Bandhan Bank Ltd'},
                 'BANKBARODA': {'ticker': '18047', 'description': 'Bank of Baroda Ltd'},
                 'BANKINDIA': {'ticker': '18031', 'description': 'Bank of India Ltd'},
                 'BATAINDIA': {'ticker': '18034', 'description': 'Bata India Ltd'},
                 'BBTC': {'ticker': '100245', 'description': 'Bombay Burmah Trading Corporation Ltd'},
                 'BEL': {'ticker': '18043', 'description': 'Bharat Electronics Ltd'},
                 'BERGEPAINT': {'ticker': '18036', 'description': 'Berger Paints India Ltd'},
                 'BHARATFIN': {'ticker': '18391', 'description': 'Bharat Financial Inclusion Ltd'},
                 'BHARATFORG': {'ticker': '18039', 'description': 'Bharat Forge Ltd'},
                 'BHARTIARTL': {'ticker': '18041', 'description': 'Bharti Airtel Ltd.'},
                 'BHEL': {'ticker': '18042', 'description': 'Bharat Heavy Electricals Ltd.'},
                 'BIOCON': {'ticker': '18045', 'description': 'Biocon Ltd.'},
                 'BOSCHLTD': {'ticker': '18052', 'description': 'Bosch Ltd'},
                 'BPCL': {'ticker': '18040', 'description': 'Bharat Petroleum Corp. Ltd.'},
                 'BRITANNIA': {'ticker': '18054', 'description': 'Britannia Industries Ltd'},
                 'BSOFT': {'ticker': '18261', 'description': 'Birlasoft Ltd'},
                 'CADILAHC': {'ticker': '18055', 'description': 'Cadila Healthcare Ltd.'},
                 'CANBK': {'ticker': '18057', 'description': 'Canara Bank Ltd'},
                 'CASTROLIND': {'ticker': '18061', 'description': 'Castrol India Ltd'},
                 'CENTURYTEX': {'ticker': '18065', 'description': 'Century Textiles & Industries Ltd.'},
                 'CESC': {'ticker': '18066', 'description': 'CESC Ltd'},
                 'CHOLAFIN': {'ticker': '18070', 'description': 'Cholamandalam Investment and Finance Company Ltd'},
                 'CIPLA': {'ticker': '18071', 'description': 'Cipla Ltd.'},
                 'COALINDIA': {'ticker': '18075', 'description': 'Coal India Ltd'},
                 'COLPAL': {'ticker': '18076', 'description': 'Colgate-Palmolive (India) Ltd.'},
                 'CONCOR': {'ticker': '18077', 'description': 'Container Corporation of India Ltd'},
                 'COROMANDEL': {'ticker': '18080', 'description': 'Coromandel International Ltd'},
                 'CROMPTON': {'ticker': '978762', 'description': 'Crompton Greaves Consumer Electricals Ltd'},
                 'CUMMINSIND': {'ticker': '18084', 'description': 'Cummins India Ltd'},
                 'DABUR': {'ticker': '18086', 'description': 'Dabur India Ltd.'},
                 'DBL': {'ticker': '986320', 'description': 'Dilip Buildcon Ltd'},
                 'DHFL': {'ticker': '18094', 'description': 'Dewan Housing Finance Corp. Ltd.'},
                 'DISHTV': {'ticker': '18097', 'description': 'Dish TV India Ltd'},
                 'DIVISLAB': {'ticker': '18099', 'description': "Divi's Laboratories Ltd."},
                 'DLF': {'ticker': '18100', 'description': 'DLF Ltd'},
                 'DRREDDY': {'ticker': '18101', 'description': 'Dr. Reddy’s Laboratories Ltd'},
                 'EDELWEISS': {'ticker': '18106', 'description': 'Edelweiss Financial Services Ltd.'},
                 'EICHERMOT': {'ticker': '18108', 'description': 'Eicher Motors Ltd.'},
                 'ENDURANCE': {'ticker': '992809', 'description': 'Endurance Technologies Cn Ltd'},
                 'ENGINERSIN': {'ticker': '18114', 'description': 'Engineers India Ltd.'},
                 'EQUITAS': {'ticker': '976491', 'description': 'Equitas Holdings Ltd'},
                 'ESCORTS': {'ticker': '18118', 'description': 'Escorts Ltd'},
                 'EXIDEIND': {'ticker': '18122', 'description': 'Exide Industries Ltd.'},
                 'FCONSUMER': {'ticker': '18135', 'description': 'Future Consumer Ltd'},
                 'FEDERALBNK': {'ticker': '18125', 'description': 'Federal Bank Ltd.'},
                 'FRETAIL': {'ticker': '986634', 'description': 'Future Retail Ltd'},
                 'GAIL': {'ticker': '18137', 'description': 'GAIL Ltd'},
                 'GICRE': {'ticker': '1052418', 'description': 'General Insurance Corporation of India'},
                 'GLENMARK': {'ticker': '18149', 'description': 'Glenmark Pharmaceuticals Ltd'},
                 'GMRINFRA': {'ticker': '18150', 'description': 'GMR Infrastructure Ltd'},
                 'GODREJAGRO': {'ticker': '1052259', 'description': 'Godrej Agrovet Ltd'},
                 'GODREJCP': {'ticker': '18152', 'description': 'Godrej Consumer Products Ltd.'},
                 'GODREJIND': {'ticker': '18153', 'description': 'Godrej Industries Ltd.'},
                 'GRAPHITE': {'ticker': '18155', 'description': 'Graphite India Ltd.'},
                 'GRASIM': {'ticker': '18156', 'description': 'Grasim Industries Ltd'},
                 'GRUH': {'ticker': '39867', 'description': 'GRUH Finance Ltd'},
                 'GSKCONS': {'ticker': '18148', 'description': 'GlaxoSmithKline Consumer Healthcare Ltd'},
                 'GSPL': {'ticker': '18170', 'description': 'Gujarat State Petronet Ltd.'},
                 'HAVELLS': {'ticker': '18174', 'description': 'Havells India Ltd'},
                 'HCLTECH': {'ticker': '18176', 'description': 'HCL Technologies Ltd'},
                 'HDFC': {'ticker': '18191', 'description': 'Housing Development Finance Corporation Ltd'},
                 'HDFCAMC': {'ticker': '1089258', 'description': 'HDFC Asset Management Company Ltd'},
                 'HDFCBANK': {'ticker': '18177', 'description': 'HDFC Bank Ltd'},
                 'HDFCLIFE': {'ticker': '1054973', 'description': 'HDFC Life Insurance Company Ltd'},
                 'HEG': {'ticker': '18178', 'description': 'HEG Ltd.'},
                 'HEROMOTOCO': {'ticker': '18179', 'description': 'Hero MotoCorp Ltd'},
                 'HEXAWARE': {'ticker': '18180', 'description': 'Hexaware Technologies Ltd.'},
                 'HINDALCO': {'ticker': '18187', 'description': 'Hindalco Industries Ltd.'},
                 'HINDPETRO': {'ticker': '18184', 'description': 'Hindustan Petroleum Corporation Ltd'},
                 'HINDUNILVR': {'ticker': '18185', 'description': 'Hindustan Unilever Ltd.'},
                 'HINDZINC': {'ticker': '18186', 'description': 'Hindustan Zinc Ltd.'},
                 'HUDCO': {'ticker': '1010531', 'description': 'Housing and Urban Development Corporation Ltd'},
                 'IBULHSGFIN': {'ticker': '100254', 'description': 'Indiabulls Housing Finance Ltd'},
                 'IBVENTURES': {'ticker': '18203', 'description': 'Indiabulls Ventures Ltd'},
                 'ICICIBANK': {'ticker': '18198', 'description': 'ICICI Bank Ltd'},
                 'ICICIGI': {'ticker': '1050153', 'description': 'ICICI Lombard General Insurance Company Ltd'},
                 'ICICIPRULI': {'ticker': '991131', 'description': 'ICICI Prudential Life Insurance Company Ltd'},
                 'IDBI': {'ticker': '18199', 'description': 'IDBI Bank Ltd'},
                 'IDFCFIRSTB': {'ticker': '960765', 'description': 'IDFC Bank Ltd'},
                 'IGL': {'ticker': '18213', 'description': 'Indraprastha Gas Ltd'},
                 'INDHOTEL': {'ticker': '18210', 'description': 'Indian Hotels Co. Ltd'},
                 'INDIANB': {'ticker': '18209', 'description': 'Indian Bank'},
                 'INDIGO': {'ticker': '961701', 'description': 'Interglobe Aviation Ltd'},
                 'INDUSINDBK': {'ticker': '18215', 'description': 'IndusInd Bank Ltd.'},
                 'INFY': {'ticker': '18217', 'description': 'Infosys Ltd'},
                 'IOC': {'ticker': '18197', 'description': 'Indian Oil Corporation Ltd'},
                 'ITC': {'ticker': '18224', 'description': 'ITC Ltd'},
                 'INFRATEL': {'ticker': '39852', 'description': 'Bharti Infratel'},
                 'JINDALSTEL': {'ticker': '18241', 'description': 'Jindal Steel & Power Ltd'},
                 'JSWENERGY': {'ticker': '18244', 'description': 'JSW Energy Ltd'},
                 'JSWSTEEL': {'ticker': '18226', 'description': 'JSW Steel Ltd'},
                 'JUBILANT': {'ticker': '18246', 'description': 'Jubilant Lifescienes Ltd'},
                 'JUBLFOOD': {'ticker': '18247', 'description': 'Jubilant Foodworks Ltd'},
                 'JUSTDIAL': {'ticker': '100244', 'description': 'Just Dial Ltd'},
                 'KAJARIACER': {'ticker': '18251', 'description': 'Kajaria Ceramics Ltd'},
                 'KOTAKBANK': {'ticker': '18260', 'description': 'Kotak Mahindra Bank Ltd.'},
                 'L&TFH': {'ticker': '39882', 'description': 'Lic Housing Finance Ltd.'},
                 'LICHSGFIN': {'ticker': '18269', 'description': 'Lic Housing Finance Ltd.'},
                 'LT': {'ticker': '18268', 'description': 'Lic Housing Finance Ltd.'},
                 'LTI': {'ticker': '986039', 'description': 'Larsen & Toubro Infotech Ltd'},
                 'LTTS': {'ticker': '991132', 'description': 'L&T Technology Services Ltd'},
                 'LUPIN': {'ticker': '18270', 'description': 'Lupin Ltd'},
                 'M&M': {'ticker': '18273', 'description': 'Mahindra & mahindra'},
                 'M&MFIN': {'ticker': '18271', 'description': 'Mahindra & mahindra Finance Ltd.'},
                 'MANAPPURAM': {'ticker': '39888', 'description': 'Manappuram Finance Ltd'},
                 'MARICO': {'ticker': '18276', 'description': 'Marico Ltd'},
                 'MARUTI': {'ticker': '18277', 'description': 'Maruti Suzuki India Ltd.'},
                 'MCX': {'ticker': '39886', 'description': 'Multi Commodity Exchange of India Ltd'},
                 'MCDOWELL-N': {'ticker': '18451', 'description': 'United Spirits Ltd'},
                 'MFSL': {'ticker': '18279', 'description': 'Max Financial Services Ltd'},
                 'MGL': {'ticker': '985843', 'description': 'Mahanagar Gas Ltd'},
                 'MINDTREE': {'ticker': '18283', 'description': 'MindTree Ltd'},
                 'MOTHERSUMI': {'ticker': '18288', 'description': 'Motherson Sumi Systems Ltd.'},
                 'MPHASIS': {'ticker': '18290', 'description': 'Mphasis Ltd'},
                 'MRF': {'ticker': '18291', 'description': 'M.R.F. Ltd.'},
                 'MRPL': {'ticker': '18292', 'description': 'Mangalore Refinery and Petrochemicals Ltd'},
                 'MUTHOOTFIN': {'ticker': '39890', 'description': 'Muthoot Finance Ltd'},
                 'NATCOPHARM': {'ticker': '39891', 'description': 'Natco Pharma Ltd.'},
                 'NATIONALUM': {'ticker': '18299', 'description': 'National Aluminum Co. Ltd.'},
                 'NBCC': {'ticker': '100271', 'description': 'NBCC India Ltd'},
                 'NCC': {'ticker': '18302', 'description': 'NCC Ltd'},
                 'NESTLEIND': {'ticker': '30059', 'description': 'Nestle India Ltd'},
                 'NHPC': {'ticker': '18307', 'description': 'NHPC Ltd'},
                 'NIACL': {'ticker': '1054813', 'description': 'New India Assurance Company Ltd'},
                 'NIITTECH': {'ticker': '39893', 'description': 'NIIT Technologies Ltd'},
                 'NMDC': {'ticker': '18309', 'description': 'NMDC Ltd'},
                 'NTPC': {'ticker': '18297', 'description': 'NTPC Ltd'},
                 'OBEROIRLTY': {'ticker': '18312', 'description': 'Oberoi Realty Ltd'},
                 'OFSS': {'ticker': '18316', 'description': 'Oracle Financial Services Software Ltd'},
                 'OIL': {'ticker': '18313', 'description': 'Oil And Natural Gas Corporation Ltd'},
                 'ONGC': {'ticker': '18311', 'description': 'Oil And Natural Gas Corporation Ltd'},
                 'PAGEIND': {'ticker': '18325', 'description': 'Page Industries Ltd.'},
                 'PEL': {'ticker': '18339', 'description': 'Piramal Enterprises Ltd'},
                 'PETRONET': {'ticker': '18334', 'description': 'Petronet LNG Ltd'},
                 'PFC': {'ticker': '18341', 'description': 'Power Finance Corporation Ltd'},
                 'PFIZER': {'ticker': '18335', 'description': 'Pfizer Ltd.'},
                 'PGHH': {'ticker': '18346', 'description': 'Procter & Gamble Hygiene and Health Care Ltd'},
                 'PIDILITIND': {'ticker': '18337', 'description': 'Pidilite Industries Ltd.'},
                 'PIIND': {'ticker': '100258', 'description': 'PI Industries Ltd'},
                 'PNB': {'ticker': '18350', 'description': 'Punjab National Bank'},
                 'PNBHOUSING': {'ticker': '993203', 'description': 'PNB Housing Finance Ltd'},
                 'POWERGRID': {'ticker': '18342', 'description': 'Power Grid Corporation of India Ltd'},
                 'PRESTIGE': {'ticker': '18344', 'description': 'Prestige Estates Projects Ltd'},
                 'PVR': {'ticker': '100260', 'description': 'PVR Ltd'},
                 'QUESS': {'ticker': '985922', 'description': 'Quess Corp Ltd'},
                 'RAJESHEXPO': {'ticker': '18353', 'description': 'Rajesh Exports Ltd.'},
                 'RAYMOND': {'ticker': '18358', 'description': 'Raymond Ltd'},
                 'RBLBANK': {'ticker': '987147', 'description': 'RBL Bank Ltd'},
                 'RECLTD': {'ticker': '18371', 'description': 'REC Ltd'},
                 'RELCAPITAL': {'ticker': '18361', 'description': 'Reliance Capital Ltd'},
                 'RELIANCE': {'ticker': '18367', 'description': 'Reliance Industries Ltd'},
                 'RELINFRA': {'ticker': '18364', 'description': 'Reliance Infrastructure Ltd'},
                 'RPOWER': {'ticker': '18366', 'description': 'Reliance Power Ltd'},
                 'SAIL': {'ticker': '18399', 'description': 'Steel Authority of India Ltd.'},
                 'SBILIFE': {'ticker': '1050746', 'description': 'SBI Life Insurance Company Ltd'},
                 'SBIN': {'ticker': '18376', 'description': 'State Bank Of India'},
                 'SHREECEM': {'ticker': '18383', 'description': 'Shree Cements Ltd.'},
                 'SIEMENS': {'ticker': '18387', 'description': 'Siemens Ltd'},
                 'SPARC': {'ticker': '39910', 'description': 'Sun Pharma Advanced Research Company Ltd'},
                 'SRF': {'ticker': '18397', 'description': 'SRF Ltd'},
                 'SRTRANSFIN': {'ticker': '18386', 'description': 'Shriram Transport Finance Co. Ltd.'},
                 'STAR': {'ticker': '18403', 'description': 'Strides Pharma Science Ltd'},
                 'STRTECH': {'ticker': '18402', 'description': 'Sterlite Technologies Ltd'},
                 'SUNPHARMA': {'ticker': '18405', 'description': 'Sun Pharmaceutical Industries Ltd.'},
                 'SUNTV': {'ticker': '18406', 'description': 'Sun TV Network Ltd'},
                 'SYNGENE': {'ticker': '958336', 'description': 'Syngene International Ltd'},
                 'TATACHEM': {'ticker': '18417', 'description': 'Tata Chemicals Ltd'},
                 'TATAELXSI': {'ticker': '18421', 'description': 'Tata Elxsi Ltd'},
                 'TATAGLOBAL': {'ticker': '18422', 'description': 'Tata Global Beverages Ltd'},
                 'TATAMOTORS': {'ticker': '18425', 'description': 'Tata Motors Ltd'},
                 'TATAMTRDVR': {'ticker': '947268', 'description': 'Tata Motors DV Ltd'},
                 'TATAPOWER': {'ticker': '18426', 'description': 'Tata Power Co. Ltd'},
                 'TATASTEEL': {'ticker': '18428', 'description': 'Tata Steel Ltd'},
                 'TCS': {'ticker': '18420', 'description': 'Tata Consultancy Services Ltd.'},
                 'TECHM': {'ticker': '18429', 'description': 'Tech Mahindra Ltd'},
                 'TITAN': {'ticker': '18433', 'description': 'Titan Company Ltd'},
                 'TORNTPHARM': {'ticker': '18435', 'description': 'Torrent Pharmaceuticals Ltd.'},
                 'TORNTPOWER': {'ticker': '18436', 'description': 'Torrent Power Ltd'},
                 'TVSMOTOR': {'ticker': '18442', 'description': 'TVS Motor Company Ltd.'},
                 'UBL': {'ticker': '18449', 'description': 'United Breweries Ltd.'},
                 'UJJIVAN': {'ticker': '978766', 'description': 'Ujjivan Financial Services Ltd'},
                 'ULTRACEMCO': {'ticker': '18445', 'description': 'UltraTech Cement Ltd'},
                 'UNIONBANK': {'ticker': '18447', 'description': 'Union Bank of India Ltd'},
                 'UPL': {'ticker': '18450', 'description': 'UPL Ltd'},
                 'VARROC': {'ticker': '1084839', 'description': 'Varroc Engineering Ltd'},
                 'VEDL': {'ticker': '18377', 'description': 'Vedanta Ltd'},
                 'VGUARD': {'ticker': '39926', 'description': 'V Guard Industries Ltd'},
                 'VOLTAS': {'ticker': '18462', 'description': 'Voltas Ltd.'},
                 'WIPRO': {'ticker': '18467', 'description': 'Wipro Ltd'},
                 'YESBANK': {'ticker': '18470', 'description': 'Yes Bank Ltd'},
                 'ZEEL': {'ticker': '18471', 'description': 'Zee Entertainment Enterprises Ltd.'}}
