r"""
premium_sum_csv_jump_analyzer.py

Offline analyzer for premium-sum CSV files generated by OptionsPremiumTracker.py.

Use case
--------
Your live tracker writes rows like:

    timestamp,value
    2026-06-01 09:15:02+0530,30250.0
    2026-06-01 09:15:04+0530,30275.0

where "value" is the ATM CE+PE premium sum multiplied by lots.
This script reads those daily CSV files from a folder and finds sudden premium
jumps, for example 30000 -> 33000 = 10% jump.

Main analysis logic
-------------------
1. Only CSV files with a proper trading date in the filename are processed.
   Example accepted names:
       premium_data_2026-06-01.csv
       premium_data_20260601.csv
       premium_data_01-06-2026.csv

2. Each CSV is normalized to one row per minute. The default minute value is the
   last observed premium in that minute, because this is closest to a tradeable
   decision point. You may change MINUTE_AGG_METHOD to mean/max/min/median.

3. For every minute, the script compares current premium against the average of
   the immediately preceding BASELINE_LOOKBACK_MINUTES valid minutes.

   Example with BASELINE_LOOKBACK_MINUTES=3:
       10:04 premium is compared with average of 10:01, 10:02, 10:03.

4. A jump is flagged when:
       jump_pct >= JUMP_THRESHOLD_PCT
       and jump_abs >= MIN_ABS_JUMP_RUPEES

5. Consecutive jump minutes are grouped into one jump event so that a single
   spike does not create many duplicate event rows.

6. Excel output contains:
       - jump_events: one row per jump episode
       - daily_summary: one row per CSV/day
       - overall_summary: aggregate metrics across all days
       - monthwise_summary: monthly jump statistics
       - minute_scan: optional minute-level data with jump calculations
       - skipped_files: files/rows skipped and why
       - config: exact parameters used

Windows CMD examples
--------------------
Default folder is:
    %USERPROFILE%\Downloads\PremiumsChartsData

Run:
    python premium_sum_csv_jump_analyzer.py

Run with custom folder and 10% jump threshold:
    set CSV_DIR=G:\My Drive\Trading\PremiumsChartsData
    set JUMP_THRESHOLD_PCT=10
    set BASELINE_LOOKBACK_MINUTES=3
    set MIN_VALID_BASELINE_MINUTES=2
    python premium_sum_csv_jump_analyzer.py

Run with larger minimum rupee jump filter:
    set MIN_ABS_JUMP_RUPEES=1000
    python premium_sum_csv_jump_analyzer.py

Dependencies
------------
    pip install pandas openpyxl

This script does not use Kite, pickles, OptionTradeUtils, or live market data.
It only analyzes already-generated CSV files.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from datetime import date, datetime, time as dtime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import pandas as pd

try:
    from zoneinfo import ZoneInfo  # Python 3.9+
except Exception:  # pragma: no cover
    ZoneInfo = None  # type: ignore

try:
    import pytz  # Optional fallback for older Python setups.
except Exception:  # pragma: no cover
    pytz = None  # type: ignore


# =============================================================================
# USER CONFIG
# =============================================================================

DATA_SUBDIR = "PremiumsChartsData"


def _default_csv_dir() -> str:
    """Return the same default folder used by OptionsPremiumTracker.py."""
    user_profile = os.environ.get("USERPROFILE")
    base = Path(user_profile) if user_profile else Path.home()
    return str(base / "Downloads" / DATA_SUBDIR)


# Folder containing premium_data_YYYY-MM-DD.csv files.
CSV_DIR = os.getenv("CSV_DIR", r"G:\My Drive\Trading\PremiumsChartsData")

# Output workbook. If not supplied, a timestamped/parameterized file is written
# to the Downloads folder.
OUTPUT_XLSX = os.getenv("OUTPUT_XLSX", "").strip()

# Intraday session window. Rows outside this range are ignored.
SESSION_START_IST_TEXT = os.getenv("SESSION_START_IST", "09:15")
SESSION_END_IST_TEXT = os.getenv("SESSION_END_IST", "15:30")

# Current minute premium is compared with the average of immediately preceding
# N valid minute values.
BASELINE_LOOKBACK_MINUTES = int(os.getenv("BASELINE_LOOKBACK_MINUTES", "3"))

# With a 3-minute baseline, setting this to 2 means the script will still compute
# a baseline if one of the previous three minute values is missing.
MIN_VALID_BASELINE_MINUTES = int(os.getenv("MIN_VALID_BASELINE_MINUTES", "2"))

# Percentage threshold for a jump. Example: 10 means 30000 -> 33000 is a jump.
JUMP_THRESHOLD_PCT = float(os.getenv("JUMP_THRESHOLD_PCT", "10"))

# Absolute rupee filter. Keep this 0 unless you want to ignore small rupee jumps.
MIN_ABS_JUMP_RUPEES = float(os.getenv("MIN_ABS_JUMP_RUPEES", "0"))

# Minute aggregation method. The tracker may write every 2 seconds; analysis is
# easier and more stable after reducing to one value per minute.
# Allowed: last, mean, median, max, min, first
MINUTE_AGG_METHOD = os.getenv("MINUTE_AGG_METHOD", "last").strip().lower()

# Only process files whose filename contains a proper date. This matches your
# instruction to ignore CSVs without proper dates.
REQUIRE_DATE_IN_FILENAME = os.getenv("REQUIRE_DATE_IN_FILENAME", "1").strip() == "1"

# If the file name has date 2026-06-01 but some CSV rows contain another date,
# those mismatched rows are removed. This prevents accidental cross-day pollution.
ENFORCE_FILENAME_DATE = os.getenv("ENFORCE_FILENAME_DATE", "1").strip() == "1"

# If a timestamp column contains only HH:MM:SS, the filename date is attached.
ALLOW_TIME_ONLY_TIMESTAMPS = os.getenv("ALLOW_TIME_ONLY_TIMESTAMPS", "1").strip() == "1"

# Write minute-level details. Useful for debugging, but can make Excel larger.
OUTPUT_MINUTE_SCAN = os.getenv("OUTPUT_MINUTE_SCAN", "1").strip() == "1"

# Optional label printed in summary sheets. Since the CSV has only timestamp and
# premium sum, the underlying cannot be reconstructed reliably from CSV contents.
INSTRUMENT_LABEL = os.getenv("INSTRUMENT_LABEL", "ATM_PREMIUM_SUM").strip() or "ATM_PREMIUM_SUM"

# Continue past bad files instead of failing the full run.
FAIL_ON_CSV_ERROR = os.getenv("FAIL_ON_CSV_ERROR", "0").strip() == "1"

# Number of minutes after a jump event to record follow-through/reversal data.
POST_EVENT_LOOKAHEAD_MINUTES = int(os.getenv("POST_EVENT_LOOKAHEAD_MINUTES", "5"))

# Ignore days with fewer than this many valid one-minute premium points.
MIN_VALID_MINUTES_PER_DAY = int(os.getenv("MIN_VALID_MINUTES_PER_DAY", "20"))


# =============================================================================
# BASIC HELPERS
# =============================================================================


def parse_hhmm(text: str) -> dtime:
    """Parse HH:MM text into datetime.time."""
    hh, mm = text.strip().split(":")
    return dtime(int(hh), int(mm))


SESSION_START_IST = parse_hhmm(SESSION_START_IST_TEXT)
SESSION_END_IST = parse_hhmm(SESSION_END_IST_TEXT)


def ist_tz() -> Any:
    """Return an Asia/Kolkata/Calcutta timezone object usable by pandas."""
    if ZoneInfo is not None:
        return ZoneInfo("Asia/Kolkata")
    if pytz is not None:
        return pytz.timezone("Asia/Calcutta")
    # Last-resort string accepted by pandas in most environments.
    return "Asia/Kolkata"


INDIA_TZ = ist_tz()


def _safe_fname_part(value: Any) -> str:
    """Return a filesystem-safe text fragment."""
    s = str(value)
    return "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in s)


def _downloads_folder() -> Path:
    """Return Downloads folder if it exists, otherwise home folder."""
    downloads = Path.home() / "Downloads"
    return downloads if downloads.exists() else Path.home()


def default_output_path() -> str:
    """Build default Excel output path."""
    name = (
        "premium_sum_csv_jump_analysis"
        f"_LB{_safe_fname_part(BASELINE_LOOKBACK_MINUTES)}"
        f"_MIN{_safe_fname_part(MIN_VALID_BASELINE_MINUTES)}"
        f"_TH{_safe_fname_part(JUMP_THRESHOLD_PCT)}pct"
        f"_ABS{_safe_fname_part(MIN_ABS_JUMP_RUPEES)}"
        f"_{_safe_fname_part(MINUTE_AGG_METHOD)}.xlsx"
    )
    return str(_downloads_folder() / name)


if not OUTPUT_XLSX:
    OUTPUT_XLSX = default_output_path()


# =============================================================================
# DATE / TIMESTAMP PARSING
# =============================================================================

# Date patterns accepted in filenames.
# The first pattern accepts 2026-06-01, 2026_06_01, and 20260601.
# The second accepts 01-06-2026 and 01_06_2026.
_FILENAME_DATE_PATTERNS = [
    re.compile(r"(?<!\d)(20\d{2})[-_]?([01]\d)[-_]?([0-3]\d)(?!\d)"),
    re.compile(r"(?<!\d)([0-3]\d)[-_]([01]\d)[-_](20\d{2})(?!\d)"),
]

# Matches strings ending with timezone suffix: Z, +0530, +05:30, -0400, etc.
_TZ_SUFFIX_RE = re.compile(r"(?:Z|[+-]\d{2}:?\d{2})$", re.IGNORECASE)

# Detects whether a text contains a full date.
_DATE_IN_TEXT_RE = re.compile(
    r"(?:\d{4}[-/]\d{1,2}[-/]\d{1,2})|(?:\d{1,2}[-/]\d{1,2}[-/]\d{4})"
)

# Detects HH:MM or HH:MM:SS.
_TIME_IN_TEXT_RE = re.compile(r"^\s*\d{1,2}:\d{2}(:\d{2})?(\.\d+)?\s*$")


def extract_date_from_filename(path: Path) -> Optional[date]:
    """Extract a valid trading date from a CSV filename."""
    name = path.name
    for i, pat in enumerate(_FILENAME_DATE_PATTERNS):
        m = pat.search(name)
        if not m:
            continue
        try:
            if i == 0:
                yyyy, mm, dd = int(m.group(1)), int(m.group(2)), int(m.group(3))
            else:
                dd, mm, yyyy = int(m.group(1)), int(m.group(2)), int(m.group(3))
            return date(yyyy, mm, dd)
        except ValueError:
            return None
    return None


def parse_timestamp_series_to_ist(s: pd.Series, file_day: Optional[date]) -> pd.Series:
    """
    Convert a timestamp Series to timezone-aware IST.

    Handles:
      - timezone-aware strings, e.g. 2026-06-01 09:15:02+0530
      - naive datetime strings, e.g. 2026-06-01 09:15:02
      - time-only strings, e.g. 09:15:02, by attaching file_day
    """
    s_str = s.astype("string").str.strip()

    # Convert pure time strings to full datetime strings using the filename date.
    if file_day is not None and ALLOW_TIME_ONLY_TIMESTAMPS:
        is_time_only = s_str.str.match(_TIME_IN_TEXT_RE, na=False)
        date_prefix = file_day.strftime("%Y-%m-%d")
        s_str = s_str.where(~is_time_only, date_prefix + " " + s_str)

    has_tz = s_str.str.contains(_TZ_SUFFIX_RE, regex=True, na=False)

    # Rows with timezone suffix are parsed as aware and then converted to IST.
    aware = pd.to_datetime(s_str.where(has_tz), errors="coerce", utc=True).dt.tz_convert(INDIA_TZ)

    # Rows without timezone suffix are treated as already-IST naive timestamps.
    naive = pd.to_datetime(s_str.where(~has_tz), errors="coerce")
    naive = naive.dt.tz_localize(INDIA_TZ, nonexistent="shift_forward", ambiguous="NaT")

    return aware.fillna(naive)


# =============================================================================
# CSV NORMALIZATION
# =============================================================================


def normalize_col_name(col: Any) -> str:
    """Normalize a CSV column name for matching."""
    return re.sub(r"[^a-z0-9]+", "_", str(col).strip().lower()).strip("_")


TIMESTAMP_COL_CANDIDATES = {
    "timestamp",
    "time_stamp",
    "datetime",
    "date_time",
    "date",
    "time",
    "ts",
}

VALUE_COL_CANDIDATES = {
    "value",
    "premium",
    "premium_sum",
    "premiumsum",
    "atm_premium_sum",
    "atm_premium",
    "option_premium_value",
    "premium_value",
    "premium_rupees",
    "sum",
}


@dataclass
class ReadResult:
    """Normalized raw data read from one CSV file."""

    raw_df: pd.DataFrame
    timestamp_col: str
    value_col: str
    assumed_headerless: bool


@dataclass
class FileResult:
    """Analysis result for one CSV/trading day."""

    minute_scan: pd.DataFrame
    jump_events: pd.DataFrame
    daily_summary: Dict[str, Any]
    skipped_rows: List[Dict[str, Any]]


def read_csv_flex(path: Path) -> pd.DataFrame:
    """Read a CSV with common encodings."""
    last_err: Optional[Exception] = None
    for enc in ("utf-8-sig", "utf-8", "cp1252", "latin1"):
        try:
            return pd.read_csv(path, encoding=enc)
        except Exception as exc:
            last_err = exc
    if last_err is not None:
        raise last_err
    raise RuntimeError(f"Could not read CSV: {path}")


def read_csv_headerless(path: Path) -> pd.DataFrame:
    """Read a CSV as headerless two-column data."""
    last_err: Optional[Exception] = None
    for enc in ("utf-8-sig", "utf-8", "cp1252", "latin1"):
        try:
            return pd.read_csv(path, encoding=enc, header=None)
        except Exception as exc:
            last_err = exc
    if last_err is not None:
        raise last_err
    raise RuntimeError(f"Could not read headerless CSV: {path}")


def choose_timestamp_and_value_columns(df: pd.DataFrame) -> Optional[Tuple[str, str]]:
    """
    Choose timestamp and premium-value columns from a possibly renamed CSV.

    Preferred schema from OptionsPremiumTracker.py is timestamp,value.
    Fallback: first datetime-like column + first mostly numeric column.
    """
    if df.empty or len(df.columns) < 2:
        return None

    norm_to_original: Dict[str, str] = {normalize_col_name(c): c for c in df.columns}

    timestamp_col: Optional[str] = None
    value_col: Optional[str] = None

    for cand in TIMESTAMP_COL_CANDIDATES:
        if cand in norm_to_original:
            timestamp_col = norm_to_original[cand]
            break

    for cand in VALUE_COL_CANDIDATES:
        if cand in norm_to_original:
            value_col = norm_to_original[cand]
            break

    if timestamp_col and value_col and timestamp_col != value_col:
        return timestamp_col, value_col

    # Fallback: infer timestamp column by parse success ratio.
    best_ts_col: Optional[str] = None
    best_ts_score = -1.0
    for col in df.columns:
        sample = df[col].dropna().astype("string").head(200)
        if sample.empty:
            continue
        # Basic prefilter prevents a numeric premium column from being parsed as
        # weird epoch-like dates.
        text_has_date_or_time = sample.str.contains(_DATE_IN_TEXT_RE, regex=True, na=False) | sample.str.contains(
            r"\d{1,2}:\d{2}", regex=True, na=False
        )
        if text_has_date_or_time.mean() < 0.5:
            continue
        parsed = pd.to_datetime(sample, errors="coerce")
        score = float(parsed.notna().mean())
        if score > best_ts_score:
            best_ts_score = score
            best_ts_col = col

    timestamp_col = timestamp_col or best_ts_col

    # Fallback: infer premium column by numeric conversion ratio.
    best_val_col: Optional[str] = None
    best_val_score = -1.0
    for col in df.columns:
        if col == timestamp_col:
            continue
        sample = df[col].dropna().astype("string").head(500)
        if sample.empty:
            continue
        cleaned = sample.str.replace(",", "", regex=False).str.replace("₹", "", regex=False).str.strip()
        numeric = pd.to_numeric(cleaned, errors="coerce")
        score = float(numeric.notna().mean())
        if score > best_val_score:
            best_val_score = score
            best_val_col = col

    value_col = value_col or best_val_col

    if timestamp_col is None or value_col is None or timestamp_col == value_col:
        return None
    return timestamp_col, value_col


def load_and_normalize_csv(path: Path, file_day: Optional[date]) -> ReadResult:
    """Read one CSV and return a normalized timestamp/value DataFrame."""
    df = read_csv_flex(path)
    chosen = choose_timestamp_and_value_columns(df)
    assumed_headerless = False

    # If normal read did not detect the two columns, retry as headerless.
    if chosen is None:
        df2 = read_csv_headerless(path)
        if df2.shape[1] < 2:
            raise ValueError("CSV does not contain at least two columns")
        df2 = df2.iloc[:, :2].copy()
        df2.columns = ["timestamp", "value"]
        df = df2
        chosen = ("timestamp", "value")
        assumed_headerless = True

    ts_col, val_col = chosen
    out = df[[ts_col, val_col]].copy()
    out.columns = ["timestamp_raw", "premium_raw"]

    out["timestamp"] = parse_timestamp_series_to_ist(out["timestamp_raw"], file_day=file_day)

    # Clean rupee symbols and thousands separators before numeric conversion.
    premium_text = out["premium_raw"].astype("string")
    premium_text = premium_text.str.replace(",", "", regex=False).str.replace("₹", "", regex=False).str.strip()
    out["premium"] = pd.to_numeric(premium_text, errors="coerce")

    return ReadResult(raw_df=out, timestamp_col=str(ts_col), value_col=str(val_col), assumed_headerless=assumed_headerless)


# =============================================================================
# JUMP DETECTION
# =============================================================================


def full_session_index(day_d: date) -> pd.DatetimeIndex:
    """Create complete 1-minute IST index for the configured session."""
    start = pd.Timestamp(datetime.combine(day_d, SESSION_START_IST), tz=INDIA_TZ)
    end = pd.Timestamp(datetime.combine(day_d, SESSION_END_IST), tz=INDIA_TZ)
    return pd.date_range(start=start, end=end, freq="1min")


def aggregate_to_minutes(raw: pd.DataFrame, day_d: date) -> pd.DataFrame:
    """
    Convert raw tick/second-level premium rows into one row per minute.

    The returned DataFrame is reindexed to the full session. Missing minutes are
    kept as NaN so that the rolling baseline does not silently invent data.
    """
    if MINUTE_AGG_METHOD not in {"last", "mean", "median", "max", "min", "first"}:
        raise ValueError(
            "MINUTE_AGG_METHOD must be one of: last, mean, median, max, min, first. "
            f"Got: {MINUTE_AGG_METHOD}"
        )

    tmp = raw.dropna(subset=["timestamp", "premium"]).copy()
    tmp = tmp.sort_values("timestamp")
    tmp["minute"] = tmp["timestamp"].dt.floor("min")

    grouped = tmp.groupby("minute", as_index=True)
    if MINUTE_AGG_METHOD == "last":
        premium = grouped["premium"].last()
    elif MINUTE_AGG_METHOD == "first":
        premium = grouped["premium"].first()
    elif MINUTE_AGG_METHOD == "mean":
        premium = grouped["premium"].mean()
    elif MINUTE_AGG_METHOD == "median":
        premium = grouped["premium"].median()
    elif MINUTE_AGG_METHOD == "max":
        premium = grouped["premium"].max()
    elif MINUTE_AGG_METHOD == "min":
        premium = grouped["premium"].min()
    else:  # pragma: no cover
        raise AssertionError("unreachable")

    agg = pd.DataFrame({"premium": premium})
    agg["raw_points_in_minute"] = grouped["premium"].size()
    agg["premium_first_in_minute"] = grouped["premium"].first()
    agg["premium_last_in_minute"] = grouped["premium"].last()
    agg["premium_min_in_minute"] = grouped["premium"].min()
    agg["premium_max_in_minute"] = grouped["premium"].max()

    idx = full_session_index(day_d)
    minute_df = pd.DataFrame(index=idx)
    minute_df.index.name = "minute"
    minute_df = minute_df.join(agg, how="left")
    return minute_df


def add_jump_columns(minute_df: pd.DataFrame) -> pd.DataFrame:
    """Add rolling-baseline and jump columns to a one-minute premium DataFrame."""
    out = minute_df.copy()
    premium = pd.to_numeric(out["premium"], errors="coerce")

    previous = premium.shift(1)
    baseline_source = premium.shift(1)
    rolling = baseline_source.rolling(
        window=BASELINE_LOOKBACK_MINUTES,
        min_periods=MIN_VALID_BASELINE_MINUTES,
    )

    out["previous_premium"] = previous
    out["baseline_avg"] = rolling.mean()
    out["baseline_min"] = rolling.min()
    out["baseline_max"] = rolling.max()
    out["baseline_std"] = rolling.std(ddof=0)
    out["baseline_valid_minutes"] = rolling.count()

    out["jump_abs"] = premium - out["baseline_avg"]
    out["jump_pct"] = (out["jump_abs"] / out["baseline_avg"]) * 100.0
    out["jump_vs_prev_abs"] = premium - out["previous_premium"]
    out["jump_vs_prev_pct"] = (out["jump_vs_prev_abs"] / out["previous_premium"]) * 100.0

    out["drop_abs"] = out["baseline_avg"] - premium
    out["drop_pct"] = (out["drop_abs"] / out["baseline_avg"]) * 100.0

    out["jump_flag"] = (
        premium.notna()
        & out["baseline_avg"].notna()
        & (out["baseline_avg"] > 0)
        & (out["jump_abs"] >= MIN_ABS_JUMP_RUPEES)
        & (out["jump_pct"] >= JUMP_THRESHOLD_PCT)
    )

    out["time"] = out.index.strftime("%H:%M")
    return out


def build_jump_events(minute_df: pd.DataFrame, *, source_file: str, day_d: date) -> pd.DataFrame:
    """Group consecutive jump-flag minutes into jump events."""
    if minute_df.empty or "jump_flag" not in minute_df.columns:
        return pd.DataFrame()

    flags = minute_df["jump_flag"].fillna(False).astype(bool)
    if not flags.any():
        return pd.DataFrame()

    # Consecutive True blocks become event_id 1, 2, 3, ...
    start_of_event = flags & ~flags.shift(1, fill_value=False)
    event_id_series = start_of_event.cumsum().where(flags)

    rows: List[Dict[str, Any]] = []
    session_start_ts = pd.Timestamp(datetime.combine(day_d, SESSION_START_IST), tz=INDIA_TZ)

    for event_id in sorted(event_id_series.dropna().unique()):
        event_mask = event_id_series.eq(event_id)
        event = minute_df.loc[event_mask].copy()
        if event.empty:
            continue

        start_ts = event.index[0]
        end_ts = event.index[-1]
        peak_ts = event["jump_pct"].idxmax()
        peak = minute_df.loc[peak_ts]
        start_row = minute_df.loc[start_ts]

        duration_min = int((end_ts - start_ts).total_seconds() // 60) + 1
        minutes_from_open = int((start_ts - session_start_ts).total_seconds() // 60)

        # Follow-through after the event. This tells whether a jump immediately
        # kept expanding or reverted in the next few minutes.
        lookahead_end_ts = end_ts + pd.Timedelta(minutes=POST_EVENT_LOOKAHEAD_MINUTES)
        future = minute_df.loc[(minute_df.index > end_ts) & (minute_df.index <= lookahead_end_ts)]
        future_valid = future[future["premium"].notna()]

        if future_valid.empty:
            premium_after_n = float("nan")
            max_premium_after_n = float("nan")
            min_premium_after_n = float("nan")
            post_event_change_from_peak_pct = float("nan")
        else:
            premium_after_n = float(future_valid["premium"].iloc[-1])
            max_premium_after_n = float(future_valid["premium"].max())
            min_premium_after_n = float(future_valid["premium"].min())
            peak_premium = float(peak["premium"])
            post_event_change_from_peak_pct = (
                ((premium_after_n - peak_premium) / peak_premium) * 100.0 if peak_premium > 0 else float("nan")
            )

        rows.append(
            {
                "day": day_d,
                "instrument_label": INSTRUMENT_LABEL,
                "source_file": source_file,
                "event_id": int(event_id),
                "event_start_time": start_ts.strftime("%H:%M"),
                "event_peak_time": peak_ts.strftime("%H:%M"),
                "event_end_time": end_ts.strftime("%H:%M"),
                "duration_minutes": duration_min,
                "minutes_from_open": minutes_from_open,
                "baseline_lookback_minutes": BASELINE_LOOKBACK_MINUTES,
                "baseline_valid_minutes_at_start": int(start_row.get("baseline_valid_minutes", 0) or 0),
                "baseline_avg_at_start": float(start_row.get("baseline_avg", float("nan"))),
                "previous_premium_at_start": float(start_row.get("previous_premium", float("nan"))),
                "premium_at_start": float(start_row.get("premium", float("nan"))),
                "start_jump_abs": float(start_row.get("jump_abs", float("nan"))),
                "start_jump_pct": float(start_row.get("jump_pct", float("nan"))),
                "peak_premium": float(peak.get("premium", float("nan"))),
                "peak_jump_abs": float(peak.get("jump_abs", float("nan"))),
                "peak_jump_pct": float(peak.get("jump_pct", float("nan"))),
                "peak_jump_vs_prev_abs": float(peak.get("jump_vs_prev_abs", float("nan"))),
                "peak_jump_vs_prev_pct": float(peak.get("jump_vs_prev_pct", float("nan"))),
                "avg_jump_pct_during_event": float(event["jump_pct"].mean()),
                "avg_jump_abs_during_event": float(event["jump_abs"].mean()),
                "max_premium_next_n_minutes": max_premium_after_n,
                "min_premium_next_n_minutes": min_premium_after_n,
                "premium_after_n_minutes": premium_after_n,
                "post_event_change_from_peak_pct": post_event_change_from_peak_pct,
                "lookahead_minutes": POST_EVENT_LOOKAHEAD_MINUTES,
            }
        )

    return pd.DataFrame(rows)


# =============================================================================
# DAILY SUMMARY
# =============================================================================


def safe_float(value: Any, default: float = 0.0) -> float:
    """Convert value to float without raising on NaN/object errors."""
    try:
        v = float(value)
        if pd.isna(v):
            return default
        return v
    except Exception:
        return default


def summarize_day(
    *,
    source_file: str,
    day_d: date,
    raw_rows: int,
    rows_after_date_filter: int,
    rows_after_session_filter: int,
    minute_df: pd.DataFrame,
    events_df: pd.DataFrame,
    timestamp_col: str,
    value_col: str,
    assumed_headerless: bool,
) -> Dict[str, Any]:
    """Build one summary row for a CSV/trading day."""
    valid_minutes = minute_df[minute_df["premium"].notna()].copy()

    if valid_minutes.empty:
        first_time = None
        last_time = None
        open_premium = close_premium = min_premium = max_premium = avg_premium = float("nan")
        day_range_abs = day_range_pct = float("nan")
    else:
        first_time = valid_minutes.index[0].strftime("%H:%M")
        last_time = valid_minutes.index[-1].strftime("%H:%M")
        open_premium = float(valid_minutes["premium"].iloc[0])
        close_premium = float(valid_minutes["premium"].iloc[-1])
        min_premium = float(valid_minutes["premium"].min())
        max_premium = float(valid_minutes["premium"].max())
        avg_premium = float(valid_minutes["premium"].mean())
        day_range_abs = max_premium - min_premium
        day_range_pct = (day_range_abs / open_premium * 100.0) if open_premium > 0 else float("nan")

    jump_minutes = int(minute_df["jump_flag"].fillna(False).sum()) if "jump_flag" in minute_df.columns else 0
    event_count = int(len(events_df))

    if events_df.empty:
        first_jump_time = None
        largest_jump_time = None
        largest_jump_pct = 0.0
        largest_jump_abs = 0.0
        avg_event_peak_jump_pct = 0.0
        avg_event_peak_jump_abs = 0.0
        median_event_peak_jump_pct = 0.0
        max_event_duration_minutes = 0
        avg_events_per_day_marker = 0.0
    else:
        first_jump_time = str(events_df["event_start_time"].iloc[0])
        peak_idx = events_df["peak_jump_pct"].idxmax()
        largest_jump_time = str(events_df.loc[peak_idx, "event_peak_time"])
        largest_jump_pct = float(events_df["peak_jump_pct"].max())
        largest_jump_abs = float(events_df["peak_jump_abs"].max())
        avg_event_peak_jump_pct = float(events_df["peak_jump_pct"].mean())
        avg_event_peak_jump_abs = float(events_df["peak_jump_abs"].mean())
        median_event_peak_jump_pct = float(events_df["peak_jump_pct"].median())
        max_event_duration_minutes = int(events_df["duration_minutes"].max())
        avg_events_per_day_marker = float(event_count)

    return {
        "day": day_d,
        "month": pd.Timestamp(day_d).strftime("%Y-%m"),
        "instrument_label": INSTRUMENT_LABEL,
        "source_file": source_file,
        "timestamp_col_used": timestamp_col,
        "value_col_used": value_col,
        "assumed_headerless_csv": assumed_headerless,
        "raw_rows": raw_rows,
        "rows_after_date_filter": rows_after_date_filter,
        "rows_after_session_filter": rows_after_session_filter,
        "valid_minute_points": int(valid_minutes.shape[0]),
        "missing_session_minutes": int(minute_df["premium"].isna().sum()),
        "first_premium_time": first_time,
        "last_premium_time": last_time,
        "open_premium": open_premium,
        "close_premium": close_premium,
        "min_premium": min_premium,
        "max_premium": max_premium,
        "avg_premium": avg_premium,
        "day_range_abs": day_range_abs,
        "day_range_pct_of_open": day_range_pct,
        "jump_threshold_pct": JUMP_THRESHOLD_PCT,
        "min_abs_jump_rupees": MIN_ABS_JUMP_RUPEES,
        "jump_events": event_count,
        "jump_minutes": jump_minutes,
        "first_jump_time": first_jump_time,
        "largest_jump_time": largest_jump_time,
        "largest_jump_pct": largest_jump_pct,
        "largest_jump_abs": largest_jump_abs,
        "avg_event_peak_jump_pct": avg_event_peak_jump_pct,
        "median_event_peak_jump_pct": median_event_peak_jump_pct,
        "avg_event_peak_jump_abs": avg_event_peak_jump_abs,
        "max_event_duration_minutes": max_event_duration_minutes,
        "events_per_day": avg_events_per_day_marker,
    }


# =============================================================================
# PER-FILE PROCESSING
# =============================================================================


def process_one_csv(path: Path) -> FileResult:
    """Process one CSV file and return minute scan, jump events, and summary."""
    file_day = extract_date_from_filename(path)
    skipped_rows: List[Dict[str, Any]] = []

    if REQUIRE_DATE_IN_FILENAME and file_day is None:
        raise ValueError("No valid trading date found in filename")

    read_res = load_and_normalize_csv(path, file_day=file_day)
    raw = read_res.raw_df.copy()
    raw_rows = int(raw.shape[0])

    invalid_ts = int(raw["timestamp"].isna().sum())
    invalid_premium = int(raw["premium"].isna().sum())
    if invalid_ts or invalid_premium:
        skipped_rows.append(
            {
                "source_file": path.name,
                "day": file_day,
                "reason": "Invalid timestamp or premium rows removed",
                "invalid_timestamp_rows": invalid_ts,
                "invalid_premium_rows": invalid_premium,
            }
        )

    raw = raw.dropna(subset=["timestamp", "premium"]).copy()
    if raw.empty:
        raise ValueError("No valid timestamp/premium rows after parsing")

    raw["local_day"] = raw["timestamp"].dt.date

    # If filename had no date and that was allowed, use the single row date.
    if file_day is None:
        unique_days = sorted(raw["local_day"].dropna().unique().tolist())
        if len(unique_days) != 1:
            raise ValueError("Filename has no date and CSV contains zero/multiple dates")
        file_day = unique_days[0]

    rows_before_date_filter = int(raw.shape[0])
    if ENFORCE_FILENAME_DATE:
        raw = raw[raw["local_day"] == file_day].copy()
    rows_after_date_filter = int(raw.shape[0])

    if rows_after_date_filter == 0:
        raise ValueError("No rows match the date extracted from filename")

    if rows_before_date_filter != rows_after_date_filter:
        skipped_rows.append(
            {
                "source_file": path.name,
                "day": file_day,
                "reason": "Rows with date different from filename date removed",
                "removed_rows": rows_before_date_filter - rows_after_date_filter,
            }
        )

    raw["local_time"] = raw["timestamp"].dt.time
    raw = raw[(raw["local_time"] >= SESSION_START_IST) & (raw["local_time"] <= SESSION_END_IST)].copy()
    rows_after_session_filter = int(raw.shape[0])

    if raw.empty:
        raise ValueError("No valid rows inside configured market session")

    # Remove exact duplicate timestamps. For live appends, keep the last value.
    duplicate_ts = int(raw.duplicated(subset=["timestamp"], keep="last").sum())
    if duplicate_ts:
        skipped_rows.append(
            {
                "source_file": path.name,
                "day": file_day,
                "reason": "Duplicate timestamps removed; last row retained",
                "duplicate_timestamp_rows": duplicate_ts,
            }
        )
    raw = raw.drop_duplicates(subset=["timestamp"], keep="last").sort_values("timestamp")

    minute_df = aggregate_to_minutes(raw, file_day)
    minute_df = add_jump_columns(minute_df)

    valid_minute_points = int(minute_df["premium"].notna().sum())
    if valid_minute_points < MIN_VALID_MINUTES_PER_DAY:
        raise ValueError(
            f"Too few valid minute points: {valid_minute_points}; "
            f"minimum required is {MIN_VALID_MINUTES_PER_DAY}"
        )

    events_df = build_jump_events(minute_df, source_file=path.name, day_d=file_day)

    # Add identity columns to minute scan after calculations.
    minute_df = minute_df.reset_index()
    minute_df.insert(0, "day", file_day)
    minute_df.insert(1, "instrument_label", INSTRUMENT_LABEL)
    minute_df.insert(2, "source_file", path.name)
    minute_df["minute"] = pd.to_datetime(minute_df["minute"]).dt.tz_convert(INDIA_TZ)
    minute_df["minute_ist"] = minute_df["minute"].dt.strftime("%Y-%m-%d %H:%M:%S%z")

    # Keep a practical order for the most important minute-level columns.
    first_cols = [
        "day",
        "instrument_label",
        "source_file",
        "minute_ist",
        "time",
        "premium",
        "previous_premium",
        "baseline_avg",
        "baseline_valid_minutes",
        "jump_abs",
        "jump_pct",
        "jump_vs_prev_abs",
        "jump_vs_prev_pct",
        "jump_flag",
    ]
    rest_cols = [c for c in minute_df.columns if c not in first_cols and c != "minute"]
    minute_df = minute_df[first_cols + rest_cols]

    summary = summarize_day(
        source_file=path.name,
        day_d=file_day,
        raw_rows=raw_rows,
        rows_after_date_filter=rows_after_date_filter,
        rows_after_session_filter=rows_after_session_filter,
        minute_df=add_jump_columns(aggregate_to_minutes(raw, file_day)),
        events_df=events_df,
        timestamp_col=read_res.timestamp_col,
        value_col=read_res.value_col,
        assumed_headerless=read_res.assumed_headerless,
    )

    return FileResult(
        minute_scan=minute_df,
        jump_events=events_df,
        daily_summary=summary,
        skipped_rows=skipped_rows,
    )


# =============================================================================
# AGGREGATE SUMMARIES
# =============================================================================


def build_overall_summary(daily_df: pd.DataFrame, events_df: pd.DataFrame) -> pd.DataFrame:
    """Build aggregate summary across all processed days."""
    if daily_df.empty:
        return pd.DataFrame()

    total_days = int(daily_df["day"].nunique())
    days_with_jump = int((daily_df["jump_events"] > 0).sum())
    total_events = int(daily_df["jump_events"].sum())

    if events_df.empty:
        row = {
            "instrument_label": INSTRUMENT_LABEL,
            "processed_days": total_days,
            "days_with_jump": days_with_jump,
            "days_with_jump_pct": 0.0,
            "total_jump_events": 0,
            "avg_jump_events_per_day": 0.0,
            "median_jump_events_per_day": float(daily_df["jump_events"].median()),
            "avg_peak_jump_pct": 0.0,
            "median_peak_jump_pct": 0.0,
            "max_peak_jump_pct": 0.0,
            "avg_peak_jump_abs": 0.0,
            "max_peak_jump_abs": 0.0,
            "avg_event_duration_minutes": 0.0,
            "max_event_duration_minutes": 0,
            "avg_daily_max_premium": float(daily_df["max_premium"].mean()),
            "avg_daily_avg_premium": float(daily_df["avg_premium"].mean()),
        }
    else:
        row = {
            "instrument_label": INSTRUMENT_LABEL,
            "processed_days": total_days,
            "days_with_jump": days_with_jump,
            "days_with_jump_pct": 100.0 * days_with_jump / total_days if total_days else 0.0,
            "total_jump_events": total_events,
            "avg_jump_events_per_day": float(daily_df["jump_events"].mean()),
            "median_jump_events_per_day": float(daily_df["jump_events"].median()),
            "avg_peak_jump_pct": float(events_df["peak_jump_pct"].mean()),
            "median_peak_jump_pct": float(events_df["peak_jump_pct"].median()),
            "max_peak_jump_pct": float(events_df["peak_jump_pct"].max()),
            "avg_peak_jump_abs": float(events_df["peak_jump_abs"].mean()),
            "max_peak_jump_abs": float(events_df["peak_jump_abs"].max()),
            "avg_event_duration_minutes": float(events_df["duration_minutes"].mean()),
            "max_event_duration_minutes": int(events_df["duration_minutes"].max()),
            "avg_daily_max_premium": float(daily_df["max_premium"].mean()),
            "avg_daily_avg_premium": float(daily_df["avg_premium"].mean()),
        }

    return pd.DataFrame([row])


def build_monthwise_summary(daily_df: pd.DataFrame, events_df: pd.DataFrame) -> pd.DataFrame:
    """Build monthly jump summary."""
    if daily_df.empty:
        return pd.DataFrame()

    base = (
        daily_df.groupby("month", as_index=False)
        .agg(
            processed_days=("day", "nunique"),
            days_with_jump=("jump_events", lambda s: int((s > 0).sum())),
            total_jump_events=("jump_events", "sum"),
            avg_jump_events_per_day=("jump_events", "mean"),
            median_jump_events_per_day=("jump_events", "median"),
            avg_daily_avg_premium=("avg_premium", "mean"),
            avg_daily_max_premium=("max_premium", "mean"),
            max_daily_largest_jump_pct=("largest_jump_pct", "max"),
            max_daily_largest_jump_abs=("largest_jump_abs", "max"),
        )
        .sort_values("month")
        .reset_index(drop=True)
    )
    base["days_with_jump_pct"] = 100.0 * base["days_with_jump"] / base["processed_days"]

    if not events_df.empty:
        e = events_df.copy()
        e["month"] = pd.to_datetime(e["day"]).dt.strftime("%Y-%m")
        event_stats = (
            e.groupby("month", as_index=False)
            .agg(
                avg_event_peak_jump_pct=("peak_jump_pct", "mean"),
                median_event_peak_jump_pct=("peak_jump_pct", "median"),
                max_event_peak_jump_pct=("peak_jump_pct", "max"),
                avg_event_peak_jump_abs=("peak_jump_abs", "mean"),
                max_event_peak_jump_abs=("peak_jump_abs", "max"),
                avg_event_duration_minutes=("duration_minutes", "mean"),
                max_event_duration_minutes=("duration_minutes", "max"),
            )
            .reset_index(drop=True)
        )
        base = base.merge(event_stats, on="month", how="left")

    return base


# =============================================================================
# EXCEL OUTPUT
# =============================================================================


def config_df() -> pd.DataFrame:
    """Return configuration as a two-column DataFrame."""
    rows = {
        "CSV_DIR": CSV_DIR,
        "OUTPUT_XLSX": OUTPUT_XLSX,
        "SESSION_START_IST": SESSION_START_IST_TEXT,
        "SESSION_END_IST": SESSION_END_IST_TEXT,
        "BASELINE_LOOKBACK_MINUTES": BASELINE_LOOKBACK_MINUTES,
        "MIN_VALID_BASELINE_MINUTES": MIN_VALID_BASELINE_MINUTES,
        "JUMP_THRESHOLD_PCT": JUMP_THRESHOLD_PCT,
        "MIN_ABS_JUMP_RUPEES": MIN_ABS_JUMP_RUPEES,
        "MINUTE_AGG_METHOD": MINUTE_AGG_METHOD,
        "REQUIRE_DATE_IN_FILENAME": REQUIRE_DATE_IN_FILENAME,
        "ENFORCE_FILENAME_DATE": ENFORCE_FILENAME_DATE,
        "ALLOW_TIME_ONLY_TIMESTAMPS": ALLOW_TIME_ONLY_TIMESTAMPS,
        "OUTPUT_MINUTE_SCAN": OUTPUT_MINUTE_SCAN,
        "INSTRUMENT_LABEL": INSTRUMENT_LABEL,
        "POST_EVENT_LOOKAHEAD_MINUTES": POST_EVENT_LOOKAHEAD_MINUTES,
        "MIN_VALID_MINUTES_PER_DAY": MIN_VALID_MINUTES_PER_DAY,
    }
    return pd.DataFrame([{"parameter": k, "value": v} for k, v in rows.items()])


def autosize_columns(ws: Any, max_width: int = 42) -> None:
    """Autosize worksheet columns safely."""
    for column_cells in ws.columns:
        try:
            col_letter = column_cells[0].column_letter
        except Exception:
            continue
        max_len = 0
        for cell in column_cells[:2000]:
            if cell.value is None:
                continue
            max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = max(10, min(max_width, max_len + 2))


def apply_excel_formatting(writer: pd.ExcelWriter) -> None:
    """Apply basic formatting to all workbook sheets."""
    try:
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
    except Exception:
        return

    wb = writer.book
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_font = Font(color="FFFFFF", bold=True)
    thin = Side(style="thin", color="D9E2F3")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    pct_cols = {"jump_pct", "jump_vs_prev_pct", "drop_pct", "largest_jump_pct", "avg_event_peak_jump_pct", "median_event_peak_jump_pct", "days_with_jump_pct", "day_range_pct_of_open", "post_event_change_from_peak_pct", "max_peak_jump_pct", "median_peak_jump_pct", "avg_peak_jump_pct", "max_event_peak_jump_pct"}
    rupee_cols = {"premium", "previous_premium", "baseline_avg", "baseline_min", "baseline_max", "jump_abs", "jump_vs_prev_abs", "drop_abs", "open_premium", "close_premium", "min_premium", "max_premium", "avg_premium", "day_range_abs", "largest_jump_abs", "avg_event_peak_jump_abs", "peak_premium", "peak_jump_abs", "start_jump_abs", "baseline_avg_at_start", "previous_premium_at_start", "premium_at_start", "max_premium_next_n_minutes", "min_premium_next_n_minutes", "premium_after_n_minutes"}

    for ws in wb.worksheets:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions

        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            cell.border = border

        # Apply light borders and number formats.
        headers = [cell.value for cell in ws[1]]
        for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
            for cell in row:
                cell.border = border
                if cell.column <= len(headers):
                    header = headers[cell.column - 1]
                    if header in pct_cols:
                        cell.number_format = "0.00"
                    elif header in rupee_cols:
                        cell.number_format = "#,##0.00"
                    elif header in {"day"}:
                        cell.number_format = "yyyy-mm-dd"

        autosize_columns(ws)

        # Cap long text columns more tightly.
        for idx, header in enumerate(headers, start=1):
            if header in {"source_file", "reason", "OUTPUT_XLSX", "CSV_DIR"}:
                ws.column_dimensions[get_column_letter(idx)].width = min(ws.column_dimensions[get_column_letter(idx)].width, 55)


def write_excel(
    *,
    jump_events_df: pd.DataFrame,
    daily_df: pd.DataFrame,
    overall_df: pd.DataFrame,
    monthwise_df: pd.DataFrame,
    minute_scan_df: pd.DataFrame,
    skipped_df: pd.DataFrame,
) -> None:
    """Write all analysis outputs to Excel."""
    out_path = Path(OUTPUT_XLSX)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        jump_events_df.to_excel(writer, sheet_name="jump_events", index=False)
        daily_df.to_excel(writer, sheet_name="daily_summary", index=False)
        overall_df.to_excel(writer, sheet_name="overall_summary", index=False)
        monthwise_df.to_excel(writer, sheet_name="monthwise_summary", index=False)
        if OUTPUT_MINUTE_SCAN:
            minute_scan_df.to_excel(writer, sheet_name="minute_scan", index=False)
        skipped_df.to_excel(writer, sheet_name="skipped_files", index=False)
        config_df().to_excel(writer, sheet_name="config", index=False)
        apply_excel_formatting(writer)

    print(f"[DONE] Excel written: {out_path}")


# =============================================================================
# MAIN
# =============================================================================


def list_csv_files(csv_dir: str) -> List[Path]:
    """Return sorted CSV files from the configured folder."""
    folder = Path(csv_dir)
    if not folder.exists():
        raise FileNotFoundError(f"CSV_DIR does not exist: {folder}")
    return sorted(p for p in folder.glob("*.csv") if p.is_file())


def main() -> None:
    """Run full folder analysis."""
    csv_paths = list_csv_files(CSV_DIR)
    if not csv_paths:
        raise FileNotFoundError(f"No CSV files found in: {CSV_DIR}")

    print(f"[INFO] CSV files found: {len(csv_paths)}")
    print(f"[INFO] CSV_DIR: {CSV_DIR}")
    print(f"[INFO] Output: {OUTPUT_XLSX}")
    print(
        "[INFO] Jump rule: "
        f"current minute >= avg(previous {BASELINE_LOOKBACK_MINUTES} valid minutes) "
        f"+ {JUMP_THRESHOLD_PCT:.2f}% and abs jump >= {MIN_ABS_JUMP_RUPEES:.2f}"
    )

    all_minute_scans: List[pd.DataFrame] = []
    all_events: List[pd.DataFrame] = []
    daily_rows: List[Dict[str, Any]] = []
    skipped_rows: List[Dict[str, Any]] = []

    for path in csv_paths:
        file_day = extract_date_from_filename(path)
        if REQUIRE_DATE_IN_FILENAME and file_day is None:
            skipped_rows.append(
                {
                    "source_file": path.name,
                    "day": None,
                    "reason": "Skipped: no valid date in filename",
                }
            )
            print(f"[SKIP] {path.name}: no valid date in filename")
            continue

        try:
            result = process_one_csv(path)
            all_minute_scans.append(result.minute_scan)
            if not result.jump_events.empty:
                all_events.append(result.jump_events)
            daily_rows.append(result.daily_summary)
            skipped_rows.extend(result.skipped_rows)
            print(
                f"[OK] {path.name}: valid_minutes={result.daily_summary['valid_minute_points']} "
                f"jump_events={result.daily_summary['jump_events']} "
                f"largest_jump_pct={result.daily_summary['largest_jump_pct']:.2f}"
            )
        except Exception as exc:
            skipped_rows.append(
                {
                    "source_file": path.name,
                    "day": file_day,
                    "reason": f"Skipped: {exc}",
                }
            )
            msg = f"[WARN] {path.name}: {exc}"
            if FAIL_ON_CSV_ERROR:
                raise RuntimeError(msg) from exc
            print(msg)

    minute_scan_df = pd.concat(all_minute_scans, ignore_index=True) if all_minute_scans else pd.DataFrame()
    jump_events_df = pd.concat(all_events, ignore_index=True) if all_events else pd.DataFrame()
    daily_df = pd.DataFrame(daily_rows)
    skipped_df = pd.DataFrame(skipped_rows)

    if not daily_df.empty:
        daily_df = daily_df.sort_values(["day", "source_file"]).reset_index(drop=True)
    if not jump_events_df.empty:
        jump_events_df = jump_events_df.sort_values(["day", "source_file", "event_id"]).reset_index(drop=True)
    if not minute_scan_df.empty:
        minute_scan_df = minute_scan_df.sort_values(["day", "source_file", "minute_ist"]).reset_index(drop=True)

    overall_df = build_overall_summary(daily_df, jump_events_df)
    monthwise_df = build_monthwise_summary(daily_df, jump_events_df)

    write_excel(
        jump_events_df=jump_events_df,
        daily_df=daily_df,
        overall_df=overall_df,
        monthwise_df=monthwise_df,
        minute_scan_df=minute_scan_df,
        skipped_df=skipped_df,
    )

    if daily_df.empty:
        print("[WARN] No valid daily CSVs processed. Check skipped_files sheet.")
    else:
        print("\n[SUMMARY]")
        print(f"Processed days/files: {len(daily_df)}")
        print(f"Total jump events: {int(daily_df['jump_events'].sum())}")
        print(f"Days with at least one jump: {int((daily_df['jump_events'] > 0).sum())}")
        if not jump_events_df.empty:
            print(f"Average peak jump pct: {jump_events_df['peak_jump_pct'].mean():.2f}%")
            print(f"Maximum peak jump pct: {jump_events_df['peak_jump_pct'].max():.2f}%")
            print(f"Average peak jump rupees: {jump_events_df['peak_jump_abs'].mean():.2f}")
            print(f"Maximum peak jump rupees: {jump_events_df['peak_jump_abs'].max():.2f}")


if __name__ == "__main__":
    main()
r"""
premium_sum_csv_jump_analyzer.py

Offline analyzer for premium-sum CSV files generated by OptionsPremiumTracker.py.

Use case
--------
Your live tracker writes rows like:

    timestamp,value
    2026-06-01 09:15:02+0530,30250.0
    2026-06-01 09:15:04+0530,30275.0

where "value" is the ATM CE+PE premium sum multiplied by lots.
This script reads those daily CSV files from a folder and finds sudden premium
jumps, for example 30000 -> 33000 = 10% jump.

Main analysis logic
-------------------
1. Only CSV files with a proper trading date in the filename are processed.
   Example accepted names:
       premium_data_2026-06-01.csv
       premium_data_20260601.csv
       premium_data_01-06-2026.csv

2. Each CSV is normalized to one row per minute. The default minute value is the
   last observed premium in that minute, because this is closest to a tradeable
   decision point. You may change MINUTE_AGG_METHOD to mean/max/min/median.

3. For every minute, the script compares current premium against the average of
   the immediately preceding BASELINE_LOOKBACK_MINUTES valid minutes.

   Example with BASELINE_LOOKBACK_MINUTES=3:
       10:04 premium is compared with average of 10:01, 10:02, 10:03.

4. A jump is flagged when:
       jump_pct >= JUMP_THRESHOLD_PCT
       and jump_abs >= MIN_ABS_JUMP_RUPEES

5. Consecutive jump minutes are grouped into one jump event so that a single
   spike does not create many duplicate event rows.

6. Excel output contains:
       - jump_events: one row per jump episode
       - daily_summary: one row per CSV/day
       - overall_summary: aggregate metrics across all days
       - monthwise_summary: monthly jump statistics
       - minute_scan: optional minute-level data with jump calculations
       - skipped_files: files/rows skipped and why
       - config: exact parameters used

Windows CMD examples
--------------------
Default folder is:
    %USERPROFILE%\Downloads\PremiumsChartsData

Run:
    python premium_sum_csv_jump_analyzer.py

Run with custom folder and 10% jump threshold:
    set CSV_DIR=G:\My Drive\Trading\PremiumsChartsData
    set JUMP_THRESHOLD_PCT=10
    set BASELINE_LOOKBACK_MINUTES=3
    set MIN_VALID_BASELINE_MINUTES=2
    python premium_sum_csv_jump_analyzer.py

Run with larger minimum rupee jump filter:
    set MIN_ABS_JUMP_RUPEES=1000
    python premium_sum_csv_jump_analyzer.py

Dependencies
------------
    pip install pandas openpyxl

This script does not use Kite, pickles, OptionTradeUtils, or live market data.
It only analyzes already-generated CSV files.
"""

import os
import re
from dataclasses import dataclass
from datetime import date, datetime, time as dtime
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import pandas as pd

try:
    from zoneinfo import ZoneInfo  # Python 3.9+
except Exception:  # pragma: no cover
    ZoneInfo = None  # type: ignore

try:
    import pytz  # Optional fallback for older Python setups.
except Exception:  # pragma: no cover
    pytz = None  # type: ignore


# =============================================================================
# USER CONFIG
# =============================================================================

DATA_SUBDIR = "PremiumsChartsData"


def _default_csv_dir() -> str:
    """Return the same default folder used by OptionsPremiumTracker.py."""
    user_profile = os.environ.get("USERPROFILE")
    base = Path(user_profile) if user_profile else Path.home()
    return str(base / "Downloads" / DATA_SUBDIR)


# Folder containing premium_data_YYYY-MM-DD.csv files.
CSV_DIR = os.getenv("CSV_DIR", _default_csv_dir())

# Output workbook. If not supplied, a timestamped/parameterized file is written
# to the Downloads folder.
OUTPUT_XLSX = os.getenv("OUTPUT_XLSX", "").strip()

# Intraday session window. Rows outside this range are ignored.
SESSION_START_IST_TEXT = os.getenv("SESSION_START_IST", "09:15")
SESSION_END_IST_TEXT = os.getenv("SESSION_END_IST", "15:30")

# Current minute premium is compared with the average of immediately preceding
# N valid minute values.
BASELINE_LOOKBACK_MINUTES = int(os.getenv("BASELINE_LOOKBACK_MINUTES", "3"))

# With a 3-minute baseline, setting this to 2 means the script will still compute
# a baseline if one of the previous three minute values is missing.
MIN_VALID_BASELINE_MINUTES = int(os.getenv("MIN_VALID_BASELINE_MINUTES", "2"))

# Percentage threshold for a jump. Example: 10 means 30000 -> 33000 is a jump.
JUMP_THRESHOLD_PCT = float(os.getenv("JUMP_THRESHOLD_PCT", "10"))

# Absolute rupee filter. Keep this 0 unless you want to ignore small rupee jumps.
MIN_ABS_JUMP_RUPEES = float(os.getenv("MIN_ABS_JUMP_RUPEES", "0"))

# Minute aggregation method. The tracker may write every 2 seconds; analysis is
# easier and more stable after reducing to one value per minute.
# Allowed: last, mean, median, max, min, first
MINUTE_AGG_METHOD = os.getenv("MINUTE_AGG_METHOD", "last").strip().lower()

# Only process files whose filename contains a proper date. This matches your
# instruction to ignore CSVs without proper dates.
REQUIRE_DATE_IN_FILENAME = os.getenv("REQUIRE_DATE_IN_FILENAME", "1").strip() == "1"

# If the file name has date 2026-06-01 but some CSV rows contain another date,
# those mismatched rows are removed. This prevents accidental cross-day pollution.
ENFORCE_FILENAME_DATE = os.getenv("ENFORCE_FILENAME_DATE", "1").strip() == "1"

# If a timestamp column contains only HH:MM:SS, the filename date is attached.
ALLOW_TIME_ONLY_TIMESTAMPS = os.getenv("ALLOW_TIME_ONLY_TIMESTAMPS", "1").strip() == "1"

# Write minute-level details. Useful for debugging, but can make Excel larger.
OUTPUT_MINUTE_SCAN = os.getenv("OUTPUT_MINUTE_SCAN", "1").strip() == "1"

# Optional label printed in summary sheets. Since the CSV has only timestamp and
# premium sum, the underlying cannot be reconstructed reliably from CSV contents.
INSTRUMENT_LABEL = os.getenv("INSTRUMENT_LABEL", "ATM_PREMIUM_SUM").strip() or "ATM_PREMIUM_SUM"

# Continue past bad files instead of failing the full run.
FAIL_ON_CSV_ERROR = os.getenv("FAIL_ON_CSV_ERROR", "0").strip() == "1"

# Number of minutes after a jump event to record follow-through/reversal data.
POST_EVENT_LOOKAHEAD_MINUTES = int(os.getenv("POST_EVENT_LOOKAHEAD_MINUTES", "5"))

# Ignore days with fewer than this many valid one-minute premium points.
MIN_VALID_MINUTES_PER_DAY = int(os.getenv("MIN_VALID_MINUTES_PER_DAY", "20"))


# =============================================================================
# BASIC HELPERS
# =============================================================================


def parse_hhmm(text: str) -> dtime:
    """Parse HH:MM text into datetime.time."""
    hh, mm = text.strip().split(":")
    return dtime(int(hh), int(mm))


SESSION_START_IST = parse_hhmm(SESSION_START_IST_TEXT)
SESSION_END_IST = parse_hhmm(SESSION_END_IST_TEXT)


def ist_tz() -> Any:
    """Return an Asia/Kolkata/Calcutta timezone object usable by pandas."""
    if ZoneInfo is not None:
        return ZoneInfo("Asia/Kolkata")
    if pytz is not None:
        return pytz.timezone("Asia/Calcutta")
    # Last-resort string accepted by pandas in most environments.
    return "Asia/Kolkata"


INDIA_TZ = ist_tz()


def _safe_fname_part(value: Any) -> str:
    """Return a filesystem-safe text fragment."""
    s = str(value)
    return "".join(ch if ch.isalnum() or ch in ("-", "_") else "_" for ch in s)


def _downloads_folder() -> Path:
    """Return Downloads folder if it exists, otherwise home folder."""
    downloads = Path.home() / "Downloads"
    return downloads if downloads.exists() else Path.home()


def default_output_path() -> str:
    """Build default Excel output path."""
    name = (
        "premium_sum_csv_jump_analysis"
        f"_LB{_safe_fname_part(BASELINE_LOOKBACK_MINUTES)}"
        f"_MIN{_safe_fname_part(MIN_VALID_BASELINE_MINUTES)}"
        f"_TH{_safe_fname_part(JUMP_THRESHOLD_PCT)}pct"
        f"_ABS{_safe_fname_part(MIN_ABS_JUMP_RUPEES)}"
        f"_{_safe_fname_part(MINUTE_AGG_METHOD)}.xlsx"
    )
    return str(_downloads_folder() / name)


if not OUTPUT_XLSX:
    OUTPUT_XLSX = default_output_path()


# =============================================================================
# DATE / TIMESTAMP PARSING
# =============================================================================

# Date patterns accepted in filenames.
# The first pattern accepts 2026-06-01, 2026_06_01, and 20260601.
# The second accepts 01-06-2026 and 01_06_2026.
_FILENAME_DATE_PATTERNS = [
    re.compile(r"(?<!\d)(20\d{2})[-_]?([01]\d)[-_]?([0-3]\d)(?!\d)"),
    re.compile(r"(?<!\d)([0-3]\d)[-_]([01]\d)[-_](20\d{2})(?!\d)"),
]

# Matches strings ending with timezone suffix: Z, +0530, +05:30, -0400, etc.
_TZ_SUFFIX_RE = re.compile(r"(?:Z|[+-]\d{2}:?\d{2})$", re.IGNORECASE)

# Detects whether a text contains a full date.
_DATE_IN_TEXT_RE = re.compile(
    r"(?:\d{4}[-/]\d{1,2}[-/]\d{1,2})|(?:\d{1,2}[-/]\d{1,2}[-/]\d{4})"
)

# Detects HH:MM or HH:MM:SS.
_TIME_IN_TEXT_RE = re.compile(r"^\s*\d{1,2}:\d{2}(:\d{2})?(\.\d+)?\s*$")


def extract_date_from_filename(path: Path) -> Optional[date]:
    """Extract a valid trading date from a CSV filename."""
    name = path.name
    for i, pat in enumerate(_FILENAME_DATE_PATTERNS):
        m = pat.search(name)
        if not m:
            continue
        try:
            if i == 0:
                yyyy, mm, dd = int(m.group(1)), int(m.group(2)), int(m.group(3))
            else:
                dd, mm, yyyy = int(m.group(1)), int(m.group(2)), int(m.group(3))
            return date(yyyy, mm, dd)
        except ValueError:
            return None
    return None


def parse_timestamp_series_to_ist(s: pd.Series, file_day: Optional[date]) -> pd.Series:
    """
    Convert a timestamp Series to timezone-aware IST.

    Handles:
      - timezone-aware strings, e.g. 2026-06-01 09:15:02+0530
      - naive datetime strings, e.g. 2026-06-01 09:15:02
      - time-only strings, e.g. 09:15:02, by attaching file_day
    """
    s_str = s.astype("string").str.strip()

    # Convert pure time strings to full datetime strings using the filename date.
    if file_day is not None and ALLOW_TIME_ONLY_TIMESTAMPS:
        is_time_only = s_str.str.match(_TIME_IN_TEXT_RE, na=False)
        date_prefix = file_day.strftime("%Y-%m-%d")
        s_str = s_str.where(~is_time_only, date_prefix + " " + s_str)

    has_tz = s_str.str.contains(_TZ_SUFFIX_RE, regex=True, na=False)

    # Rows with timezone suffix are parsed as aware and then converted to IST.
    aware = pd.to_datetime(s_str.where(has_tz), errors="coerce", utc=True).dt.tz_convert(INDIA_TZ)

    # Rows without timezone suffix are treated as already-IST naive timestamps.
    naive = pd.to_datetime(s_str.where(~has_tz), errors="coerce")
    naive = naive.dt.tz_localize(INDIA_TZ, nonexistent="shift_forward", ambiguous="NaT")

    return aware.fillna(naive)


# =============================================================================
# CSV NORMALIZATION
# =============================================================================


def normalize_col_name(col: Any) -> str:
    """Normalize a CSV column name for matching."""
    return re.sub(r"[^a-z0-9]+", "_", str(col).strip().lower()).strip("_")


TIMESTAMP_COL_CANDIDATES = {
    "timestamp",
    "time_stamp",
    "datetime",
    "date_time",
    "date",
    "time",
    "ts",
}

VALUE_COL_CANDIDATES = {
    "value",
    "premium",
    "premium_sum",
    "premiumsum",
    "atm_premium_sum",
    "atm_premium",
    "option_premium_value",
    "premium_value",
    "premium_rupees",
    "sum",
}


@dataclass
class ReadResult:
    """Normalized raw data read from one CSV file."""

    raw_df: pd.DataFrame
    timestamp_col: str
    value_col: str
    assumed_headerless: bool


@dataclass
class FileResult:
    """Analysis result for one CSV/trading day."""

    minute_scan: pd.DataFrame
    jump_events: pd.DataFrame
    daily_summary: Dict[str, Any]
    skipped_rows: List[Dict[str, Any]]


def read_csv_flex(path: Path) -> pd.DataFrame:
    """Read a CSV with common encodings."""
    last_err: Optional[Exception] = None
    for enc in ("utf-8-sig", "utf-8", "cp1252", "latin1"):
        try:
            return pd.read_csv(path, encoding=enc)
        except Exception as exc:
            last_err = exc
    if last_err is not None:
        raise last_err
    raise RuntimeError(f"Could not read CSV: {path}")


def read_csv_headerless(path: Path) -> pd.DataFrame:
    """Read a CSV as headerless two-column data."""
    last_err: Optional[Exception] = None
    for enc in ("utf-8-sig", "utf-8", "cp1252", "latin1"):
        try:
            return pd.read_csv(path, encoding=enc, header=None)
        except Exception as exc:
            last_err = exc
    if last_err is not None:
        raise last_err
    raise RuntimeError(f"Could not read headerless CSV: {path}")


def choose_timestamp_and_value_columns(df: pd.DataFrame) -> Optional[Tuple[str, str]]:
    """
    Choose timestamp and premium-value columns from a possibly renamed CSV.

    Preferred schema from OptionsPremiumTracker.py is timestamp,value.
    Fallback: first datetime-like column + first mostly numeric column.
    """
    if df.empty or len(df.columns) < 2:
        return None

    norm_to_original: Dict[str, str] = {normalize_col_name(c): c for c in df.columns}

    timestamp_col: Optional[str] = None
    value_col: Optional[str] = None

    for cand in TIMESTAMP_COL_CANDIDATES:
        if cand in norm_to_original:
            timestamp_col = norm_to_original[cand]
            break

    for cand in VALUE_COL_CANDIDATES:
        if cand in norm_to_original:
            value_col = norm_to_original[cand]
            break

    if timestamp_col and value_col and timestamp_col != value_col:
        return timestamp_col, value_col

    # Fallback: infer timestamp column by parse success ratio.
    best_ts_col: Optional[str] = None
    best_ts_score = -1.0
    for col in df.columns:
        sample = df[col].dropna().astype("string").head(200)
        if sample.empty:
            continue
        # Basic prefilter prevents a numeric premium column from being parsed as
        # weird epoch-like dates.
        text_has_date_or_time = sample.str.contains(_DATE_IN_TEXT_RE, regex=True, na=False) | sample.str.contains(
            r"\d{1,2}:\d{2}", regex=True, na=False
        )
        if text_has_date_or_time.mean() < 0.5:
            continue
        parsed = pd.to_datetime(sample, errors="coerce")
        score = float(parsed.notna().mean())
        if score > best_ts_score:
            best_ts_score = score
            best_ts_col = col

    timestamp_col = timestamp_col or best_ts_col

    # Fallback: infer premium column by numeric conversion ratio.
    best_val_col: Optional[str] = None
    best_val_score = -1.0
    for col in df.columns:
        if col == timestamp_col:
            continue
        sample = df[col].dropna().astype("string").head(500)
        if sample.empty:
            continue
        cleaned = sample.str.replace(",", "", regex=False).str.replace("₹", "", regex=False).str.strip()
        numeric = pd.to_numeric(cleaned, errors="coerce")
        score = float(numeric.notna().mean())
        if score > best_val_score:
            best_val_score = score
            best_val_col = col

    value_col = value_col or best_val_col

    if timestamp_col is None or value_col is None or timestamp_col == value_col:
        return None
    return timestamp_col, value_col


def load_and_normalize_csv(path: Path, file_day: Optional[date]) -> ReadResult:
    """Read one CSV and return a normalized timestamp/value DataFrame."""
    df = read_csv_flex(path)
    chosen = choose_timestamp_and_value_columns(df)
    assumed_headerless = False

    # If normal read did not detect the two columns, retry as headerless.
    if chosen is None:
        df2 = read_csv_headerless(path)
        if df2.shape[1] < 2:
            raise ValueError("CSV does not contain at least two columns")
        df2 = df2.iloc[:, :2].copy()
        df2.columns = ["timestamp", "value"]
        df = df2
        chosen = ("timestamp", "value")
        assumed_headerless = True

    ts_col, val_col = chosen
    out = df[[ts_col, val_col]].copy()
    out.columns = ["timestamp_raw", "premium_raw"]

    out["timestamp"] = parse_timestamp_series_to_ist(out["timestamp_raw"], file_day=file_day)

    # Clean rupee symbols and thousands separators before numeric conversion.
    premium_text = out["premium_raw"].astype("string")
    premium_text = premium_text.str.replace(",", "", regex=False).str.replace("₹", "", regex=False).str.strip()
    out["premium"] = pd.to_numeric(premium_text, errors="coerce")

    return ReadResult(raw_df=out, timestamp_col=str(ts_col), value_col=str(val_col), assumed_headerless=assumed_headerless)


# =============================================================================
# JUMP DETECTION
# =============================================================================


def full_session_index(day_d: date) -> pd.DatetimeIndex:
    """Create complete 1-minute IST index for the configured session."""
    start = pd.Timestamp(datetime.combine(day_d, SESSION_START_IST), tz=INDIA_TZ)
    end = pd.Timestamp(datetime.combine(day_d, SESSION_END_IST), tz=INDIA_TZ)
    return pd.date_range(start=start, end=end, freq="1min")


def aggregate_to_minutes(raw: pd.DataFrame, day_d: date) -> pd.DataFrame:
    """
    Convert raw tick/second-level premium rows into one row per minute.

    The returned DataFrame is reindexed to the full session. Missing minutes are
    kept as NaN so that the rolling baseline does not silently invent data.
    """
    if MINUTE_AGG_METHOD not in {"last", "mean", "median", "max", "min", "first"}:
        raise ValueError(
            "MINUTE_AGG_METHOD must be one of: last, mean, median, max, min, first. "
            f"Got: {MINUTE_AGG_METHOD}"
        )

    tmp = raw.dropna(subset=["timestamp", "premium"]).copy()
    tmp = tmp.sort_values("timestamp")
    tmp["minute"] = tmp["timestamp"].dt.floor("min")

    grouped = tmp.groupby("minute", as_index=True)
    if MINUTE_AGG_METHOD == "last":
        premium = grouped["premium"].last()
    elif MINUTE_AGG_METHOD == "first":
        premium = grouped["premium"].first()
    elif MINUTE_AGG_METHOD == "mean":
        premium = grouped["premium"].mean()
    elif MINUTE_AGG_METHOD == "median":
        premium = grouped["premium"].median()
    elif MINUTE_AGG_METHOD == "max":
        premium = grouped["premium"].max()
    elif MINUTE_AGG_METHOD == "min":
        premium = grouped["premium"].min()
    else:  # pragma: no cover
        raise AssertionError("unreachable")

    agg = pd.DataFrame({"premium": premium})
    agg["raw_points_in_minute"] = grouped["premium"].size()
    agg["premium_first_in_minute"] = grouped["premium"].first()
    agg["premium_last_in_minute"] = grouped["premium"].last()
    agg["premium_min_in_minute"] = grouped["premium"].min()
    agg["premium_max_in_minute"] = grouped["premium"].max()

    idx = full_session_index(day_d)
    minute_df = pd.DataFrame(index=idx)
    minute_df.index.name = "minute"
    minute_df = minute_df.join(agg, how="left")
    return minute_df


def add_jump_columns(minute_df: pd.DataFrame) -> pd.DataFrame:
    """Add rolling-baseline and jump columns to a one-minute premium DataFrame."""
    out = minute_df.copy()
    premium = pd.to_numeric(out["premium"], errors="coerce")

    previous = premium.shift(1)
    baseline_source = premium.shift(1)
    rolling = baseline_source.rolling(
        window=BASELINE_LOOKBACK_MINUTES,
        min_periods=MIN_VALID_BASELINE_MINUTES,
    )

    out["previous_premium"] = previous
    out["baseline_avg"] = rolling.mean()
    out["baseline_min"] = rolling.min()
    out["baseline_max"] = rolling.max()
    out["baseline_std"] = rolling.std(ddof=0)
    out["baseline_valid_minutes"] = rolling.count()

    out["jump_abs"] = premium - out["baseline_avg"]
    out["jump_pct"] = (out["jump_abs"] / out["baseline_avg"]) * 100.0
    out["jump_vs_prev_abs"] = premium - out["previous_premium"]
    out["jump_vs_prev_pct"] = (out["jump_vs_prev_abs"] / out["previous_premium"]) * 100.0

    out["drop_abs"] = out["baseline_avg"] - premium
    out["drop_pct"] = (out["drop_abs"] / out["baseline_avg"]) * 100.0

    out["jump_flag"] = (
        premium.notna()
        & out["baseline_avg"].notna()
        & (out["baseline_avg"] > 0)
        & (out["jump_abs"] >= MIN_ABS_JUMP_RUPEES)
        & (out["jump_pct"] >= JUMP_THRESHOLD_PCT)
    )

    out["time"] = out.index.strftime("%H:%M")
    return out


def build_jump_events(minute_df: pd.DataFrame, *, source_file: str, day_d: date) -> pd.DataFrame:
    """Group consecutive jump-flag minutes into jump events."""
    if minute_df.empty or "jump_flag" not in minute_df.columns:
        return pd.DataFrame()

    flags = minute_df["jump_flag"].fillna(False).astype(bool)
    if not flags.any():
        return pd.DataFrame()

    # Consecutive True blocks become event_id 1, 2, 3, ...
    start_of_event = flags & ~flags.shift(1, fill_value=False)
    event_id_series = start_of_event.cumsum().where(flags)

    rows: List[Dict[str, Any]] = []
    session_start_ts = pd.Timestamp(datetime.combine(day_d, SESSION_START_IST), tz=INDIA_TZ)

    for event_id in sorted(event_id_series.dropna().unique()):
        event_mask = event_id_series.eq(event_id)
        event = minute_df.loc[event_mask].copy()
        if event.empty:
            continue

        start_ts = event.index[0]
        end_ts = event.index[-1]
        peak_ts = event["jump_pct"].idxmax()
        peak = minute_df.loc[peak_ts]
        start_row = minute_df.loc[start_ts]

        duration_min = int((end_ts - start_ts).total_seconds() // 60) + 1
        minutes_from_open = int((start_ts - session_start_ts).total_seconds() // 60)

        # Follow-through after the event. This tells whether a jump immediately
        # kept expanding or reverted in the next few minutes.
        lookahead_end_ts = end_ts + pd.Timedelta(minutes=POST_EVENT_LOOKAHEAD_MINUTES)
        future = minute_df.loc[(minute_df.index > end_ts) & (minute_df.index <= lookahead_end_ts)]
        future_valid = future[future["premium"].notna()]

        if future_valid.empty:
            premium_after_n = float("nan")
            max_premium_after_n = float("nan")
            min_premium_after_n = float("nan")
            post_event_change_from_peak_pct = float("nan")
        else:
            premium_after_n = float(future_valid["premium"].iloc[-1])
            max_premium_after_n = float(future_valid["premium"].max())
            min_premium_after_n = float(future_valid["premium"].min())
            peak_premium = float(peak["premium"])
            post_event_change_from_peak_pct = (
                ((premium_after_n - peak_premium) / peak_premium) * 100.0 if peak_premium > 0 else float("nan")
            )

        rows.append(
            {
                "day": day_d,
                "instrument_label": INSTRUMENT_LABEL,
                "source_file": source_file,
                "event_id": int(event_id),
                "event_start_time": start_ts.strftime("%H:%M"),
                "event_peak_time": peak_ts.strftime("%H:%M"),
                "event_end_time": end_ts.strftime("%H:%M"),
                "duration_minutes": duration_min,
                "minutes_from_open": minutes_from_open,
                "baseline_lookback_minutes": BASELINE_LOOKBACK_MINUTES,
                "baseline_valid_minutes_at_start": int(start_row.get("baseline_valid_minutes", 0) or 0),
                "baseline_avg_at_start": float(start_row.get("baseline_avg", float("nan"))),
                "previous_premium_at_start": float(start_row.get("previous_premium", float("nan"))),
                "premium_at_start": float(start_row.get("premium", float("nan"))),
                "start_jump_abs": float(start_row.get("jump_abs", float("nan"))),
                "start_jump_pct": float(start_row.get("jump_pct", float("nan"))),
                "peak_premium": float(peak.get("premium", float("nan"))),
                "peak_jump_abs": float(peak.get("jump_abs", float("nan"))),
                "peak_jump_pct": float(peak.get("jump_pct", float("nan"))),
                "peak_jump_vs_prev_abs": float(peak.get("jump_vs_prev_abs", float("nan"))),
                "peak_jump_vs_prev_pct": float(peak.get("jump_vs_prev_pct", float("nan"))),
                "avg_jump_pct_during_event": float(event["jump_pct"].mean()),
                "avg_jump_abs_during_event": float(event["jump_abs"].mean()),
                "max_premium_next_n_minutes": max_premium_after_n,
                "min_premium_next_n_minutes": min_premium_after_n,
                "premium_after_n_minutes": premium_after_n,
                "post_event_change_from_peak_pct": post_event_change_from_peak_pct,
                "lookahead_minutes": POST_EVENT_LOOKAHEAD_MINUTES,
            }
        )

    return pd.DataFrame(rows)


# =============================================================================
# DAILY SUMMARY
# =============================================================================


def safe_float(value: Any, default: float = 0.0) -> float:
    """Convert value to float without raising on NaN/object errors."""
    try:
        v = float(value)
        if pd.isna(v):
            return default
        return v
    except Exception:
        return default


def summarize_day(
    *,
    source_file: str,
    day_d: date,
    raw_rows: int,
    rows_after_date_filter: int,
    rows_after_session_filter: int,
    minute_df: pd.DataFrame,
    events_df: pd.DataFrame,
    timestamp_col: str,
    value_col: str,
    assumed_headerless: bool,
) -> Dict[str, Any]:
    """Build one summary row for a CSV/trading day."""
    valid_minutes = minute_df[minute_df["premium"].notna()].copy()

    if valid_minutes.empty:
        first_time = None
        last_time = None
        open_premium = close_premium = min_premium = max_premium = avg_premium = float("nan")
        day_range_abs = day_range_pct = float("nan")
    else:
        first_time = valid_minutes.index[0].strftime("%H:%M")
        last_time = valid_minutes.index[-1].strftime("%H:%M")
        open_premium = float(valid_minutes["premium"].iloc[0])
        close_premium = float(valid_minutes["premium"].iloc[-1])
        min_premium = float(valid_minutes["premium"].min())
        max_premium = float(valid_minutes["premium"].max())
        avg_premium = float(valid_minutes["premium"].mean())
        day_range_abs = max_premium - min_premium
        day_range_pct = (day_range_abs / open_premium * 100.0) if open_premium > 0 else float("nan")

    jump_minutes = int(minute_df["jump_flag"].fillna(False).sum()) if "jump_flag" in minute_df.columns else 0
    event_count = int(len(events_df))

    if events_df.empty:
        first_jump_time = None
        largest_jump_time = None
        largest_jump_pct = 0.0
        largest_jump_abs = 0.0
        avg_event_peak_jump_pct = 0.0
        avg_event_peak_jump_abs = 0.0
        median_event_peak_jump_pct = 0.0
        max_event_duration_minutes = 0
        avg_events_per_day_marker = 0.0
    else:
        first_jump_time = str(events_df["event_start_time"].iloc[0])
        peak_idx = events_df["peak_jump_pct"].idxmax()
        largest_jump_time = str(events_df.loc[peak_idx, "event_peak_time"])
        largest_jump_pct = float(events_df["peak_jump_pct"].max())
        largest_jump_abs = float(events_df["peak_jump_abs"].max())
        avg_event_peak_jump_pct = float(events_df["peak_jump_pct"].mean())
        avg_event_peak_jump_abs = float(events_df["peak_jump_abs"].mean())
        median_event_peak_jump_pct = float(events_df["peak_jump_pct"].median())
        max_event_duration_minutes = int(events_df["duration_minutes"].max())
        avg_events_per_day_marker = float(event_count)

    return {
        "day": day_d,
        "month": pd.Timestamp(day_d).strftime("%Y-%m"),
        "instrument_label": INSTRUMENT_LABEL,
        "source_file": source_file,
        "timestamp_col_used": timestamp_col,
        "value_col_used": value_col,
        "assumed_headerless_csv": assumed_headerless,
        "raw_rows": raw_rows,
        "rows_after_date_filter": rows_after_date_filter,
        "rows_after_session_filter": rows_after_session_filter,
        "valid_minute_points": int(valid_minutes.shape[0]),
        "missing_session_minutes": int(minute_df["premium"].isna().sum()),
        "first_premium_time": first_time,
        "last_premium_time": last_time,
        "open_premium": open_premium,
        "close_premium": close_premium,
        "min_premium": min_premium,
        "max_premium": max_premium,
        "avg_premium": avg_premium,
        "day_range_abs": day_range_abs,
        "day_range_pct_of_open": day_range_pct,
        "jump_threshold_pct": JUMP_THRESHOLD_PCT,
        "min_abs_jump_rupees": MIN_ABS_JUMP_RUPEES,
        "jump_events": event_count,
        "jump_minutes": jump_minutes,
        "first_jump_time": first_jump_time,
        "largest_jump_time": largest_jump_time,
        "largest_jump_pct": largest_jump_pct,
        "largest_jump_abs": largest_jump_abs,
        "avg_event_peak_jump_pct": avg_event_peak_jump_pct,
        "median_event_peak_jump_pct": median_event_peak_jump_pct,
        "avg_event_peak_jump_abs": avg_event_peak_jump_abs,
        "max_event_duration_minutes": max_event_duration_minutes,
        "events_per_day": avg_events_per_day_marker,
    }


# =============================================================================
# PER-FILE PROCESSING
# =============================================================================


def process_one_csv(path: Path) -> FileResult:
    """Process one CSV file and return minute scan, jump events, and summary."""
    file_day = extract_date_from_filename(path)
    skipped_rows: List[Dict[str, Any]] = []

    if REQUIRE_DATE_IN_FILENAME and file_day is None:
        raise ValueError("No valid trading date found in filename")

    read_res = load_and_normalize_csv(path, file_day=file_day)
    raw = read_res.raw_df.copy()
    raw_rows = int(raw.shape[0])

    invalid_ts = int(raw["timestamp"].isna().sum())
    invalid_premium = int(raw["premium"].isna().sum())
    if invalid_ts or invalid_premium:
        skipped_rows.append(
            {
                "source_file": path.name,
                "day": file_day,
                "reason": "Invalid timestamp or premium rows removed",
                "invalid_timestamp_rows": invalid_ts,
                "invalid_premium_rows": invalid_premium,
            }
        )

    raw = raw.dropna(subset=["timestamp", "premium"]).copy()
    if raw.empty:
        raise ValueError("No valid timestamp/premium rows after parsing")

    raw["local_day"] = raw["timestamp"].dt.date

    # If filename had no date and that was allowed, use the single row date.
    if file_day is None:
        unique_days = sorted(raw["local_day"].dropna().unique().tolist())
        if len(unique_days) != 1:
            raise ValueError("Filename has no date and CSV contains zero/multiple dates")
        file_day = unique_days[0]

    rows_before_date_filter = int(raw.shape[0])
    if ENFORCE_FILENAME_DATE:
        raw = raw[raw["local_day"] == file_day].copy()
    rows_after_date_filter = int(raw.shape[0])

    if rows_after_date_filter == 0:
        raise ValueError("No rows match the date extracted from filename")

    if rows_before_date_filter != rows_after_date_filter:
        skipped_rows.append(
            {
                "source_file": path.name,
                "day": file_day,
                "reason": "Rows with date different from filename date removed",
                "removed_rows": rows_before_date_filter - rows_after_date_filter,
            }
        )

    raw["local_time"] = raw["timestamp"].dt.time
    raw = raw[(raw["local_time"] >= SESSION_START_IST) & (raw["local_time"] <= SESSION_END_IST)].copy()
    rows_after_session_filter = int(raw.shape[0])

    if raw.empty:
        raise ValueError("No valid rows inside configured market session")

    # Remove exact duplicate timestamps. For live appends, keep the last value.
    duplicate_ts = int(raw.duplicated(subset=["timestamp"], keep="last").sum())
    if duplicate_ts:
        skipped_rows.append(
            {
                "source_file": path.name,
                "day": file_day,
                "reason": "Duplicate timestamps removed; last row retained",
                "duplicate_timestamp_rows": duplicate_ts,
            }
        )
    raw = raw.drop_duplicates(subset=["timestamp"], keep="last").sort_values("timestamp")

    minute_df = aggregate_to_minutes(raw, file_day)
    minute_df = add_jump_columns(minute_df)

    valid_minute_points = int(minute_df["premium"].notna().sum())
    if valid_minute_points < MIN_VALID_MINUTES_PER_DAY:
        raise ValueError(
            f"Too few valid minute points: {valid_minute_points}; "
            f"minimum required is {MIN_VALID_MINUTES_PER_DAY}"
        )

    events_df = build_jump_events(minute_df, source_file=path.name, day_d=file_day)

    # Add identity columns to minute scan after calculations.
    minute_df = minute_df.reset_index()
    minute_df.insert(0, "day", file_day)
    minute_df.insert(1, "instrument_label", INSTRUMENT_LABEL)
    minute_df.insert(2, "source_file", path.name)
    minute_df["minute"] = pd.to_datetime(minute_df["minute"]).dt.tz_convert(INDIA_TZ)
    minute_df["minute_ist"] = minute_df["minute"].dt.strftime("%Y-%m-%d %H:%M:%S%z")

    # Keep a practical order for the most important minute-level columns.
    first_cols = [
        "day",
        "instrument_label",
        "source_file",
        "minute_ist",
        "time",
        "premium",
        "previous_premium",
        "baseline_avg",
        "baseline_valid_minutes",
        "jump_abs",
        "jump_pct",
        "jump_vs_prev_abs",
        "jump_vs_prev_pct",
        "jump_flag",
    ]
    rest_cols = [c for c in minute_df.columns if c not in first_cols and c != "minute"]
    minute_df = minute_df[first_cols + rest_cols]

    summary = summarize_day(
        source_file=path.name,
        day_d=file_day,
        raw_rows=raw_rows,
        rows_after_date_filter=rows_after_date_filter,
        rows_after_session_filter=rows_after_session_filter,
        minute_df=add_jump_columns(aggregate_to_minutes(raw, file_day)),
        events_df=events_df,
        timestamp_col=read_res.timestamp_col,
        value_col=read_res.value_col,
        assumed_headerless=read_res.assumed_headerless,
    )

    return FileResult(
        minute_scan=minute_df,
        jump_events=events_df,
        daily_summary=summary,
        skipped_rows=skipped_rows,
    )


# =============================================================================
# AGGREGATE SUMMARIES
# =============================================================================


def build_overall_summary(daily_df: pd.DataFrame, events_df: pd.DataFrame) -> pd.DataFrame:
    """Build aggregate summary across all processed days."""
    if daily_df.empty:
        return pd.DataFrame()

    total_days = int(daily_df["day"].nunique())
    days_with_jump = int((daily_df["jump_events"] > 0).sum())
    total_events = int(daily_df["jump_events"].sum())

    if events_df.empty:
        row = {
            "instrument_label": INSTRUMENT_LABEL,
            "processed_days": total_days,
            "days_with_jump": days_with_jump,
            "days_with_jump_pct": 0.0,
            "total_jump_events": 0,
            "avg_jump_events_per_day": 0.0,
            "median_jump_events_per_day": float(daily_df["jump_events"].median()),
            "avg_peak_jump_pct": 0.0,
            "median_peak_jump_pct": 0.0,
            "max_peak_jump_pct": 0.0,
            "avg_peak_jump_abs": 0.0,
            "max_peak_jump_abs": 0.0,
            "avg_event_duration_minutes": 0.0,
            "max_event_duration_minutes": 0,
            "avg_daily_max_premium": float(daily_df["max_premium"].mean()),
            "avg_daily_avg_premium": float(daily_df["avg_premium"].mean()),
        }
    else:
        row = {
            "instrument_label": INSTRUMENT_LABEL,
            "processed_days": total_days,
            "days_with_jump": days_with_jump,
            "days_with_jump_pct": 100.0 * days_with_jump / total_days if total_days else 0.0,
            "total_jump_events": total_events,
            "avg_jump_events_per_day": float(daily_df["jump_events"].mean()),
            "median_jump_events_per_day": float(daily_df["jump_events"].median()),
            "avg_peak_jump_pct": float(events_df["peak_jump_pct"].mean()),
            "median_peak_jump_pct": float(events_df["peak_jump_pct"].median()),
            "max_peak_jump_pct": float(events_df["peak_jump_pct"].max()),
            "avg_peak_jump_abs": float(events_df["peak_jump_abs"].mean()),
            "max_peak_jump_abs": float(events_df["peak_jump_abs"].max()),
            "avg_event_duration_minutes": float(events_df["duration_minutes"].mean()),
            "max_event_duration_minutes": int(events_df["duration_minutes"].max()),
            "avg_daily_max_premium": float(daily_df["max_premium"].mean()),
            "avg_daily_avg_premium": float(daily_df["avg_premium"].mean()),
        }

    return pd.DataFrame([row])


def build_monthwise_summary(daily_df: pd.DataFrame, events_df: pd.DataFrame) -> pd.DataFrame:
    """Build monthly jump summary."""
    if daily_df.empty:
        return pd.DataFrame()

    base = (
        daily_df.groupby("month", as_index=False)
        .agg(
            processed_days=("day", "nunique"),
            days_with_jump=("jump_events", lambda s: int((s > 0).sum())),
            total_jump_events=("jump_events", "sum"),
            avg_jump_events_per_day=("jump_events", "mean"),
            median_jump_events_per_day=("jump_events", "median"),
            avg_daily_avg_premium=("avg_premium", "mean"),
            avg_daily_max_premium=("max_premium", "mean"),
            max_daily_largest_jump_pct=("largest_jump_pct", "max"),
            max_daily_largest_jump_abs=("largest_jump_abs", "max"),
        )
        .sort_values("month")
        .reset_index(drop=True)
    )
    base["days_with_jump_pct"] = 100.0 * base["days_with_jump"] / base["processed_days"]

    if not events_df.empty:
        e = events_df.copy()
        e["month"] = pd.to_datetime(e["day"]).dt.strftime("%Y-%m")
        event_stats = (
            e.groupby("month", as_index=False)
            .agg(
                avg_event_peak_jump_pct=("peak_jump_pct", "mean"),
                median_event_peak_jump_pct=("peak_jump_pct", "median"),
                max_event_peak_jump_pct=("peak_jump_pct", "max"),
                avg_event_peak_jump_abs=("peak_jump_abs", "mean"),
                max_event_peak_jump_abs=("peak_jump_abs", "max"),
                avg_event_duration_minutes=("duration_minutes", "mean"),
                max_event_duration_minutes=("duration_minutes", "max"),
            )
            .reset_index(drop=True)
        )
        base = base.merge(event_stats, on="month", how="left")

    return base


# =============================================================================
# EXCEL OUTPUT
# =============================================================================


def config_df() -> pd.DataFrame:
    """Return configuration as a two-column DataFrame."""
    rows = {
        "CSV_DIR": CSV_DIR,
        "OUTPUT_XLSX": OUTPUT_XLSX,
        "SESSION_START_IST": SESSION_START_IST_TEXT,
        "SESSION_END_IST": SESSION_END_IST_TEXT,
        "BASELINE_LOOKBACK_MINUTES": BASELINE_LOOKBACK_MINUTES,
        "MIN_VALID_BASELINE_MINUTES": MIN_VALID_BASELINE_MINUTES,
        "JUMP_THRESHOLD_PCT": JUMP_THRESHOLD_PCT,
        "MIN_ABS_JUMP_RUPEES": MIN_ABS_JUMP_RUPEES,
        "MINUTE_AGG_METHOD": MINUTE_AGG_METHOD,
        "REQUIRE_DATE_IN_FILENAME": REQUIRE_DATE_IN_FILENAME,
        "ENFORCE_FILENAME_DATE": ENFORCE_FILENAME_DATE,
        "ALLOW_TIME_ONLY_TIMESTAMPS": ALLOW_TIME_ONLY_TIMESTAMPS,
        "OUTPUT_MINUTE_SCAN": OUTPUT_MINUTE_SCAN,
        "INSTRUMENT_LABEL": INSTRUMENT_LABEL,
        "POST_EVENT_LOOKAHEAD_MINUTES": POST_EVENT_LOOKAHEAD_MINUTES,
        "MIN_VALID_MINUTES_PER_DAY": MIN_VALID_MINUTES_PER_DAY,
    }
    return pd.DataFrame([{"parameter": k, "value": v} for k, v in rows.items()])


def autosize_columns(ws: Any, max_width: int = 42) -> None:
    """Autosize worksheet columns safely."""
    for column_cells in ws.columns:
        try:
            col_letter = column_cells[0].column_letter
        except Exception:
            continue
        max_len = 0
        for cell in column_cells[:2000]:
            if cell.value is None:
                continue
            max_len = max(max_len, len(str(cell.value)))
        ws.column_dimensions[col_letter].width = max(10, min(max_width, max_len + 2))


def apply_excel_formatting(writer: pd.ExcelWriter) -> None:
    """Apply basic formatting to all workbook sheets."""
    try:
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
    except Exception:
        return

    wb = writer.book
    header_fill = PatternFill("solid", fgColor="1F4E78")
    header_font = Font(color="FFFFFF", bold=True)
    thin = Side(style="thin", color="D9E2F3")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    pct_cols = {"jump_pct", "jump_vs_prev_pct", "drop_pct", "largest_jump_pct", "avg_event_peak_jump_pct", "median_event_peak_jump_pct", "days_with_jump_pct", "day_range_pct_of_open", "post_event_change_from_peak_pct", "max_peak_jump_pct", "median_peak_jump_pct", "avg_peak_jump_pct", "max_event_peak_jump_pct"}
    rupee_cols = {"premium", "previous_premium", "baseline_avg", "baseline_min", "baseline_max", "jump_abs", "jump_vs_prev_abs", "drop_abs", "open_premium", "close_premium", "min_premium", "max_premium", "avg_premium", "day_range_abs", "largest_jump_abs", "avg_event_peak_jump_abs", "peak_premium", "peak_jump_abs", "start_jump_abs", "baseline_avg_at_start", "previous_premium_at_start", "premium_at_start", "max_premium_next_n_minutes", "min_premium_next_n_minutes", "premium_after_n_minutes"}

    for ws in wb.worksheets:
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions

        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
            cell.border = border

        # Apply light borders and number formats.
        headers = [cell.value for cell in ws[1]]
        for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
            for cell in row:
                cell.border = border
                if cell.column <= len(headers):
                    header = headers[cell.column - 1]
                    if header in pct_cols:
                        cell.number_format = "0.00"
                    elif header in rupee_cols:
                        cell.number_format = "#,##0.00"
                    elif header in {"day"}:
                        cell.number_format = "yyyy-mm-dd"

        autosize_columns(ws)

        # Cap long text columns more tightly.
        for idx, header in enumerate(headers, start=1):
            if header in {"source_file", "reason", "OUTPUT_XLSX", "CSV_DIR"}:
                ws.column_dimensions[get_column_letter(idx)].width = min(ws.column_dimensions[get_column_letter(idx)].width, 55)


def write_excel(
    *,
    jump_events_df: pd.DataFrame,
    daily_df: pd.DataFrame,
    overall_df: pd.DataFrame,
    monthwise_df: pd.DataFrame,
    minute_scan_df: pd.DataFrame,
    skipped_df: pd.DataFrame,
) -> None:
    """Write all analysis outputs to Excel."""
    out_path = Path(OUTPUT_XLSX)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    with pd.ExcelWriter(out_path, engine="openpyxl") as writer:
        jump_events_df.to_excel(writer, sheet_name="jump_events", index=False)
        daily_df.to_excel(writer, sheet_name="daily_summary", index=False)
        overall_df.to_excel(writer, sheet_name="overall_summary", index=False)
        monthwise_df.to_excel(writer, sheet_name="monthwise_summary", index=False)
        if OUTPUT_MINUTE_SCAN:
            minute_scan_df.to_excel(writer, sheet_name="minute_scan", index=False)
        skipped_df.to_excel(writer, sheet_name="skipped_files", index=False)
        config_df().to_excel(writer, sheet_name="config", index=False)
        apply_excel_formatting(writer)

    print(f"[DONE] Excel written: {out_path}")


# =============================================================================
# MAIN
# =============================================================================


def list_csv_files(csv_dir: str) -> List[Path]:
    """Return sorted CSV files from the configured folder."""
    folder = Path(csv_dir)
    if not folder.exists():
        raise FileNotFoundError(f"CSV_DIR does not exist: {folder}")
    return sorted(p for p in folder.glob("*.csv") if p.is_file())


def main() -> None:
    """Run full folder analysis."""
    csv_paths = list_csv_files(CSV_DIR)
    if not csv_paths:
        raise FileNotFoundError(f"No CSV files found in: {CSV_DIR}")

    print(f"[INFO] CSV files found: {len(csv_paths)}")
    print(f"[INFO] CSV_DIR: {CSV_DIR}")
    print(f"[INFO] Output: {OUTPUT_XLSX}")
    print(
        "[INFO] Jump rule: "
        f"current minute >= avg(previous {BASELINE_LOOKBACK_MINUTES} valid minutes) "
        f"+ {JUMP_THRESHOLD_PCT:.2f}% and abs jump >= {MIN_ABS_JUMP_RUPEES:.2f}"
    )

    all_minute_scans: List[pd.DataFrame] = []
    all_events: List[pd.DataFrame] = []
    daily_rows: List[Dict[str, Any]] = []
    skipped_rows: List[Dict[str, Any]] = []

    for path in csv_paths:
        file_day = extract_date_from_filename(path)
        if REQUIRE_DATE_IN_FILENAME and file_day is None:
            skipped_rows.append(
                {
                    "source_file": path.name,
                    "day": None,
                    "reason": "Skipped: no valid date in filename",
                }
            )
            print(f"[SKIP] {path.name}: no valid date in filename")
            continue

        try:
            result = process_one_csv(path)
            all_minute_scans.append(result.minute_scan)
            if not result.jump_events.empty:
                all_events.append(result.jump_events)
            daily_rows.append(result.daily_summary)
            skipped_rows.extend(result.skipped_rows)
            print(
                f"[OK] {path.name}: valid_minutes={result.daily_summary['valid_minute_points']} "
                f"jump_events={result.daily_summary['jump_events']} "
                f"largest_jump_pct={result.daily_summary['largest_jump_pct']:.2f}"
            )
        except Exception as exc:
            skipped_rows.append(
                {
                    "source_file": path.name,
                    "day": file_day,
                    "reason": f"Skipped: {exc}",
                }
            )
            msg = f"[WARN] {path.name}: {exc}"
            if FAIL_ON_CSV_ERROR:
                raise RuntimeError(msg) from exc
            print(msg)

    minute_scan_df = pd.concat(all_minute_scans, ignore_index=True) if all_minute_scans else pd.DataFrame()
    jump_events_df = pd.concat(all_events, ignore_index=True) if all_events else pd.DataFrame()
    daily_df = pd.DataFrame(daily_rows)
    skipped_df = pd.DataFrame(skipped_rows)

    if not daily_df.empty:
        daily_df = daily_df.sort_values(["day", "source_file"]).reset_index(drop=True)
    if not jump_events_df.empty:
        jump_events_df = jump_events_df.sort_values(["day", "source_file", "event_id"]).reset_index(drop=True)
    if not minute_scan_df.empty:
        minute_scan_df = minute_scan_df.sort_values(["day", "source_file", "minute_ist"]).reset_index(drop=True)

    overall_df = build_overall_summary(daily_df, jump_events_df)
    monthwise_df = build_monthwise_summary(daily_df, jump_events_df)

    write_excel(
        jump_events_df=jump_events_df,
        daily_df=daily_df,
        overall_df=overall_df,
        monthwise_df=monthwise_df,
        minute_scan_df=minute_scan_df,
        skipped_df=skipped_df,
    )

    if daily_df.empty:
        print("[WARN] No valid daily CSVs processed. Check skipped_files sheet.")
    else:
        print("\n[SUMMARY]")
        print(f"Processed days/files: {len(daily_df)}")
        print(f"Total jump events: {int(daily_df['jump_events'].sum())}")
        print(f"Days with at least one jump: {int((daily_df['jump_events'] > 0).sum())}")
        if not jump_events_df.empty:
            print(f"Average peak jump pct: {jump_events_df['peak_jump_pct'].mean():.2f}%")
            print(f"Maximum peak jump pct: {jump_events_df['peak_jump_pct'].max():.2f}%")
            print(f"Average peak jump rupees: {jump_events_df['peak_jump_abs'].mean():.2f}")
            print(f"Maximum peak jump rupees: {jump_events_df['peak_jump_abs'].max():.2f}")


if __name__ == "__main__":
    main()
